routes/web.php
<?php
Route::get('/', function () { return view('auth/entrar'); });
Route::get('/login', function () { return view('auth/entrar'); });
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
// EXCEL
Route::get('import-export-view', 'ExcelController@importExportView')->name('import.export.view');
Route::post('import-file', 'ExcelController@importFile')->name('import.file');
Route::get('export-file/{type}', 'ExcelController@exportFile')->name('export.file');
// ROUTE ADM
Route::prefix('ADM')->group(function () {
  Route::resource('/adm_tipo', 'ADM\TipoC');
  Route::resource('/adm_item', 'ADM_ItemC');
  Route::post('/aprovaOrc/{id}', 'ADM\OrcamentoC@aprovaOrc')->name('aprovaOrc');
  Route::resource('/compra', 'ADM\CompraC');
  Route::resource('/g_link', 'ADM\G_LinkC');
  Route::resource('/link', 'ADM\LinkC');
  Route::resource('/orcamento', 'ADM\OrcamentoC');
  Route::resource('/pessoa', 'ADM\PessoaC');
  Route::resource('/ramo', 'EMP\RamoC');
});
//  ROUTE EMP
Route::prefix('EMP')->group(function () {
  Route::resource('/empresa', 'EMP\EmpresaC');
  Route::resource('/emp_tipo', 'EMP\TipoC');
  Route::resource('/inventario', 'EMP_InventarioC');
  Route::resource('/setor', 'EMP\SetorC');
  Route::resource('/emp_item', 'EMP_ItemC');
  Route::resource('/emp_emprestimo', 'EMP\EmprestimoC');
  Route::resource('/documento', 'TI\DocumentoC');
});
// ROUTE HRM
Route::prefix('HRM')->group(function () {
  Route::resource('/hrm_arq', 'TI\ArquivoC');
  Route::resource('/cargo', 'HRM\CargoC');
  Route::resource('/certificado', 'HRM\CertificadoC');
  Route::resource('/colaborador', 'HRM\ContratoC');
  Route::resource('/contrato', 'HRM\ContratoC');
  Route::resource('/curriculo', 'HRM\CurriculoC');
  Route::resource('/curso', 'HRM\CursoC');
  Route::resource('/exame', 'HRM\ExameC');
  Route::resource('/ferias', 'HRM\FeriasC');
  Route::resource('/ferias_pagto', 'HRM\Ferias_PagtoC');
  Route::resource('/hrm_tipo', 'HRM\TipoC');
  Route::resource('/dependente', 'HRM\DependenteC');
});
// ROUTE LOG - FROTA
Route::prefix('LOG')->group(function () {
  Route::resource('/abastecimento', 'LOG\AbastecimentoC');
  Route::resource('/documento', 'LOG\DocumentoC');
  Route::resource('/log_tipo', 'LOG\TipoC');
  Route::resource('/manutencao', 'LOG\ManutencaoC');
  Route::resource('/multa', 'LOG\MultaC');
  Route::resource('/ocorrencia', 'LOG\OcorrenciaC');
  Route::resource('/vei_seg', 'LOG\Vei_SegC');
  Route::resource('/veiculo', 'LOG\VeiculoC');
  Route::resource('/vistoria', 'LOG\VistoriaC');
});
// ROUTE LOG - MRP
Route::prefix('MRP')->group(function () {
  Route::post('/baixa_item', 'MRP\ItemC@baixa')->name('baixa_item');
  Route::resource('/emprestimo', 'MRP_EmprestimoC');
  Route::resource('/estoque', 'MRP\EstoqueC');
  Route::resource('/kit', 'MRP\KitC');
  Route::resource('/kit_item', 'MRP\Kit_ItemC');
  Route::resource('/movimento', 'MRP\MovimentoC');
  Route::post('/mrp_filtro', 'MRP\EstoqueC@mrp_filtro')->name('mrp_filtro');
  Route::resource('/mrp_item', 'MRP\ItemC');
  Route::resource('/mrp_tipo', 'MRP\TipoC');
  Route::resource('/pedido', 'MRP\PedidoC');
  Route::resource('/produto', 'MRP\ProdutoC');
  Route::get('/sts_pedido/{id}', 'MRP\PedidoC@status')->name('sts_pedido');
  Route::resource('/und', 'MRP\UndC');
});
// ROUTE TI
Route::prefix('TI')->group(function () {
  Route::resource('/help', 'TI\HelpC');
  Route::resource('/modulo', 'TI\ModuloC');
  Route::resource('/permissao', 'TI\AclC');
  Route::resource('/produtoENT', 'MRP_ProdutoEntC');
  Route::resource('/ti_tipo', 'TI\TipoC');
  Route::resource('/update', 'TI\UpdateC');
  Route::resource('/usuario', 'TI\UsuarioC');
});

/*
GET       /photos	               index	   photos.index
GET	      /photos/create	       create	   photos.create
POST	    /photos	               store	   photos.store
GET	      /photos/{photo}	       show	     photos.show
GET	      /photos/{photo}/edit   edit	     photos.edit
PUT/PATCH	/photos/{photo}        update	   photos.update
DELETE	  /photos/{photo}	       destroy	 photos.destroy
*/

app/Models/ADM/CidadeM.php
<?php namespace App\Models\ADM;

use Illuminate\Database\Eloquent\Model;
use App\Models\ADM\UfM;

class CidadeM extends Model
{
  protected $table = 'ti_cidades';
  protected $primaryKey = 'id_cidade';

  protected $fillable = [
    'id_cidade',
    'id_uf',
    'cidade',
    'cod_cidade',
    'km',
    'updated_at',
    'created_at',
    'sts_cidade'
  ];

  public function uf()    {
    return $this->hasOne(UfM::class,'id_uf','id_uf');
  }
}

app/Models/ADM/CompraM.php
<?php namespace App\Models\ADM;

use Illuminate\Database\Eloquent\Model;

class CompraM extends Model
{
  protected $table = 'adm_compras';
  protected $primaryKey = 'id_compra';

  protected $fillable = [
    'id_compra',
    'id_user',
    'id_colaborador',
    'id_aprovador',
    'id_setor',
    'compra',
    'dt_compra',
    'dt_entrega',
    'pagto',
    'valor',
    'sts_compra',
    'created_at',
    'updated_at'
  ];

  public function orcamentos()    {
    return $this->belongsToMany(OrcamentoM::class,'id_compra','id_compra');
  }
  public function setores()    {
    return $this->hasOne('App\Models\EMP_SetorM','id_setor','id_setor');
  }
}

app/Models/ADM/LinkM.php
<?php namespace App\Models\ADM;

use Illuminate\Database\Eloquent\Model;

class LinkM extends Model
{
  protected $table = 'adm_links';
  protected $primaryKey = 'id_link';

  protected $fillable = [
    'id_link','id_g_link','link','sts_link','url',
  ];

  public function glinks()    {
    return $this->hasMany(G_LinkM::class,'id_g_link','id_g_link');
  }
}

app/Http/Controllers/ADM/CompraC.php
<?php namespace App\Http\Controllers\ADM;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\ADM\CompraM;
use App\Models\ADM\OrcamentoM;
use App\Models\MRP\ItemM;

class CompraC extends Controller
{
  public $rota = ['rota'=>'compra','pasta'=>'ADM/ORC/'];

  public function carrega()  {
    $this->rota = TI_acl(H_prod(H_colaborador(H_setor($this->rota))));

    $this->rota[$this->rota['rota']] = CompraM::where('sts_'.$this->rota['rota'],'>',0)->get();
    $this->rota['orcamentos'] = OrcamentoM::where('sts_orcamento','>',0)->get();
    $this->rota['itens'] = ItemM::whereNotNull('id_compra')->get();
  }

  public function index()  {
    $this->carrega();

    return view('ADM.'.$this->rota['rota'], ['rota'=>$this->rota]);
  }

  public function show($id)  {
    $this->carrega();
    $this->rota['item'] = ItemM::where('sts_mrp_item','>',0)
                                     ->where('id_compra',$id)->get();
    $this->rota['input'] = ['id'=>$id,'rota'=>$this->rota['rota']];


    return view('ADM.adm_item', ['rota'=>$this->rota]);
  }

  // public function show($modulo)  {
  //   $this->carrega();
  //   $this->rota['modulos']   = ModuloM::where('rota',$modulo)->get();
  //
  //   return view('ADM.'.$this->rota['rota'], ['rota'=>$this->rota]);
  // }

  public function store(Request $request, CompraM $id)  {
    $data = $request->all();
    if($request->arquivo)
      $data['arquivo'] = TI_up_file($request, $this->rota['pasta'], $request[$this->rota['rota']]);

    $id->create($data);

    return redirect()->back()->with(['success' => 'Cadastrado com sucesso.']);
  }

  public function edit($id)  {
    $this->carrega();
    if($this->rota['acl']->u == 0) return redirect()->back()->with(['danger' => 'Sem acesso.']);
    $this->rota['edit'] = CompraM::findOrFail($id);
    $this->rota['orcamentos'] = OrcamentoM::where('id_compra', $id)->get();
    $this->rota['input'] = ['id'=>$id,'rota'=>$this->rota['rota']];

    return view('adm.'.$this->rota['rota'], ['rota'=>$this->rota]);
  }

  public function update(Request $request, $id)  {
    $data = $request->all();
    if($request->arquivo)
      $data['arquivo'] = TI_up_file($request, $this->rota['pasta'], $request[$this->rota['rota']]);

    $idUP = CompraM::findOrFail($id);

    if(isset($data['confirma'])){
      TI_add_fluxo('Autorizar','compra','compra',$id);// FLUXO/MODULO/ROTA/ID_ITEM
      $idUP->sts_compra = 2;
      $idUP->save();
      return redirect()->route($this->rota['rota'].'.index')->with(['success' => $this->rota['rota'].' alterado com sucesso.']);
    }
    if(isset($data['autoriza'])){
      TI_add_fluxo('Comprar','compra','compra',$id);// FLUXO/MODULO/ROTA/ID_ITEM
      $idUP->sts_compra = 3;
      $idUP->id_aprovador = \Auth::id();
      $idUP->save();
      return redirect()->route($this->rota['rota'].'.index')->with(['success' => $this->rota['rota'].' alterado com sucesso.']);
    }
    if(isset($data['finaliza'])){
      TI_del_fluxo($this->rota['rota'],$id);
      $idUP->sts_compra = 4;
      $idUP->dt_compra = date('Y-m-d');
      $idUP->save();
      return redirect()->route($this->rota['rota'].'.index')->with(['success' => $this->rota['rota'].' alterado com sucesso.']);
    }

    TI_sgs_log($this->rota['rota'],'update',$id,$idUP); // REG_LOG {ROTA|METODO|ID|OLD}
    $idUP->update($data);

    return redirect()->route($this->rota['rota'].'.index')->with(['success' => $this->rota['rota'].' alterado com sucesso.']);
  }

  public function destroy($id)  {
    TI_del_fluxo($this->rota['rota'],$id);
    $id   = CompraM::findOrFail($id);
    $id->update(['sts_'.$this->rota['rota'] => 0]);

    return redirect()->route($this->rota['rota'].'.index')->with(['success' => $this->rota['rota'].' excluído com sucesso.']);
  }
}

app/Http/Controllers/ADM/G_LinkC.php
<?php namespace App\Http\Controllers\ADM;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\ADM\G_LinkM;

class G_LinkC extends Controller
{
  public $rota = ['rota'=>'g_link'];

  public function carrega()  {
    $this->rota = TI_acl(TI_modulo($this->rota));
    $this->rota[$this->rota['rota']] = G_LinkM::where('sts_'.$this->rota['rota'],'>',0)->get();
  }

  public function index()  {
    $this->carrega();

    return view('ADM.'.$this->rota['rota'], ['rota'=>$this->rota]);
  }

  public function store(Request $request, G_LinkM $id)  {
    $log = $id->create($request->all());
    TI_sgs_log($this->rota['rota'],'store',$log['id_'.$this->rota['rota']]); // REG_LOG {ROTA|METODO|ID|OLD}

    return redirect()->route($this->rota['rota'].'.index')->with(['success' => 'Cadastrado com sucesso.']);
  }

  public function edit($id)  {
    $this->carrega();
    if($this->rota['acl']->u == 0) return redirect()->back()->with(['danger' => 'Sem acesso.']);
    $this->rota['edit'] = G_LinkM::findOrFail($id);

    return view('adm.'.$this->rota['rota'], ['rota'=>$this->rota]);
  }

  public function update(Request $request, $id)  {
    $idUP = G_LinkM::findOrFail($id);
    TI_sgs_log($this->rota['rota'],'update',$id,$idUP); // REG_LOG {ROTA|METODO|ID|OLD}
    $idUP->update($request->all());

    return redirect()->route($this->rota['rota'].'.index')->with(['success' => $this->rota['rota'].' alterado com sucesso.']);
  }

  public function destroy($id)  {
    TI_sgs_log($this->rota['rota'],'destroy',$id); // REG_LOG {ROTA|METODO|ID|OLD}
    $id = G_LinkM::findOrFail($id);
    $id->update(['sts_'.$this->rota['rota'] => 0]);

    return redirect()->route($this->rota['rota'].'.index')->with(['success' => $this->rota['rota'].' excluído com sucesso.']);
  }
}

app/Http/Controllers/ADM/LinkC.php
<?php namespace App\Http\Controllers\ADM;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\ADM\LinkM;
use App\Models\ADM\G_LinkM;

class LinkC extends Controller
{
  public $rota = ['rota'=>'link'];

  public function carrega()  {
    $this->rota = TI_acl($this->rota);
    $this->rota[$this->rota['rota']] = LinkM::where('sts_'.$this->rota['rota'],'>',0)->get();
    $this->rota['g_link'] = G_LinkM::where('sts_g_'.$this->rota['rota'],'>',0)->get();
  }

  public function index()  {
    $this->carrega();

    return view('ADM.'.$this->rota['rota'], ['rota'=>$this->rota]);
  }

  public function store(Request $request, LinkM $id)  {
    $log = $id->create($request->all());
    TI_sgs_log($this->rota['rota'],'store',$log['id_'.$this->rota['rota']]); // REG_LOG {ROTA|METODO|ID|OLD}

    return redirect()->route($this->rota['rota'].'.index')->with(['success' => 'Cadastrado com sucesso.']);
  }

  public function edit($id)  {
    $this->carrega();
    if($this->rota['acl']->u == 0) return redirect()->back()->with(['danger' => 'Sem acesso.']);
    $this->rota['edit'] = LinkM::findOrFail($id);

    return view('adm.'.$this->rota['rota'], ['rota'=>$this->rota]);
  }

  public function update(Request $request, $id)  {
    $idUP = LinkM::findOrFail($id);
    TI_sgs_log($this->rota['rota'],'update',$id,$idUP); // REG_LOG {ROTA|METODO|ID|OLD}
    $idUP->update($request->all());

    return redirect()->route($this->rota['rota'].'.index')->with(['success' => $this->rota['rota'].' alterado com sucesso.']);
  }

  public function destroy($id)  {
    TI_sgs_log($this->rota['rota'],'destroy',$id); // REG_LOG {ROTA|METODO|ID|OLD}
    $id = LinkM::findOrFail($id);
    $id->update(['sts_'.$this->rota['rota'] => 0]);

    return redirect()->route($this->rota['rota'].'.index')->with(['success' => $this->rota['rota'].' excluído com sucesso.']);
  }
}

app/Http/Controllers/ADM/OrcamentoC.php
<?php namespace App\Http\Controllers\ADM;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\ADM\OrcamentoM;
use App\Models\ADM_CompraM;

class OrcamentoC extends Controller
{
  public $rota = ['rota'=>'orcamento','pasta'=>'ADM/ORC/'];

  public function carrega()  {
    $this->rota = TI_acl(H_colaborador($this->rota));

    $this->rota[$this->rota['rota']] = OrcamentoM::where('sts_'.$this->rota['rota'],'>',0)->get();
  }

  public function index()  {
    $this->carrega();

    return view('ADM.'.$this->rota['rota'], ['rota'=>$this->rota]);
  }

  public function show($id)  {
    $this->carrega();
    $this->rota[$this->rota['rota']] = OrcamentoM::where('sts_'.$this->rota['rota'],'>',0)
                                                     ->where('id_compra', $id)->get();
    $this->rota['input'] = ['id'=>$id,'rota'=>$this->rota['rota']];
    $this->rota['compra'] = ADM_CompraM::findOrFail($id);

    return view('ADM.'.$this->rota['rota'], ['rota'=>$this->rota]);
  }

  public function store(Request $request, OrcamentoM $id)  {
    $data = $request->all();
    if($request->arquivo)
      $data['arquivo'] = TI_up_file2($request->arquivo, $this->rota['pasta'], $request[$this->rota['rota']]);

    $id->create($data);

    return redirect()->back()->with(['success' => 'Cadastrado com sucesso.']);
  }

  public function edit($id)  {
    $this->carrega();
    if($this->rota['acl']->u == 0) return redirect()->back()->with(['danger' => 'Sem acesso.']);
    $this->rota['edit'] = OrcamentoM::findOrFail($id);

    return view('adm.'.$this->rota['rota'], ['rota'=>$this->rota]);
  }

  public function update(Request $request, $id)  { dd('stop');
    $data = $request->all();
    if($request->arquivo)
      $data['arquivo'] = TI_up_file2($request->arquivo, $this->rota['pasta'], $request[$this->rota['rota']]);

    $id = OrcamentoM::findOrFail($id);
    $id->update($data);

    return redirect()->back()->with(['success' => $this->rota['rota'].' alterado com sucesso.']);
  }

  public function aprovaOrc($id)  { dd(something);
    $sts = 2;
    $idO = OrcamentoM::findOrFail($id);
    if($idO->sts_orcamento == 2) $sts = 1;
    $idO->sts_orcamento = $sts;
    $idO->save();

    return redirect()->route('compra.edit',$id)->with(['success' => $this->rota['rota'].' alterado com sucesso.']);
  }

  public function destroy($id)  {
    $id   = OrcamentoM::findOrFail($id);
    $id->update(['sts_'.$this->rota['rota'] => 0]);

    return redirect()->route($this->rota['rota'].'.index')->with(['success' => $this->rota['rota'].' excluído com sucesso.']);
  }
}

app/Http/Controllers/ADM/PessoaC.php
<?php namespace App\Http\Controllers\ADM;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\ADM\PessoaM;
use App\Models\ADM\TipoM;

class PessoaC extends Controller
{
  public $rota = ['rota' => 'pessoa'];

  public function carrega($letra = "A")  {
    $this->rota = TI_acl($this->rota);

    $this->rota[$this->rota['rota']] = PessoaM::where('sts_'.$this->rota['rota'],'>',0)->get();
    $this->rota['pess'] = PessoaM::where('sts_'.$this->rota['rota'],'>',0)
                                      ->where('pessoa','LIKE',$letra.'%')->get();
    $this->rota['tipos'] = TipoM::where('sts_adm_tipo','>',0)->get();
  }

  public function index(Request $req)  {
    $this->carrega();
    if (isset($req['id_pessoa'])) {
      return redirect()->route($this->rota['rota'].'.edit',$req['id_pessoa']);
    }

    return view('adm.'.$this->rota['rota'], ['rota'=>$this->rota]);
  }

  public function show($letra)  {
    $this->carrega($letra);

    return view('adm.'.$this->rota['rota'], ['rota'=>$this->rota]);
  }

  public function store(Request $request, PessoaM $id)  {
    $id->create($request->all());

    return redirect()->back()->with(['success' => 'Cadastrado com sucesso.']);
  }

  public function edit($id)  {
    $this->carrega();
    if($this->rota['acl']->u == 0) return redirect()->back()->with(['danger' => 'Sem acesso.']);
    $this->rota['edit'] = PessoaM::findOrFail($id);

    return view('adm.'.$this->rota['rota'], ['rota'=>$this->rota]);
  }

  public function update(Request $request, $id)  {
    $id = PessoaM::findOrFail($id);
    $id->update($request->all());

    return redirect()->route($this->rota['rota'].'.index')->with(['success' => $this->rota['rota'].' alterado com sucesso.']);
  }

  public function destroy($id)  {
    $id = PessoaM::findOrFail($id);
    $id->update(['sts_'.$this->rota['rota'] => 0]);

    return redirect()->route($this->rota['rota'].'.index')->with(['success' => $this->rota['rota'].' excluído com sucesso.']);
  }
}

resources/views/ADM/adm_tipo.blade.php
@extends('layouts.sgs')

@section('content')
  <main class="main">
    <br>
    <div class="container-fluid">
      <div class="row justify-content-center">
        <div class="col-md-12">

          @component('includes/alerts')
          @endcomponent

          <div class="card">
            {{-- START FORM --}}
            <div class="card-header">
              @if (isset($rota['edit']))
                <form action="{{ route($rota['rota'].'.update',$rota['edit']->id_adm_tipo) }}" method="post" class="form-inline">
                  <input type="hidden" name="rota" value="{{$rota[$rota['rota']][0]->rota}}">
                  @method('PUT')
              @else
                <form method="post" class="form-inline">
                  <input type="hidden" name="rota" value="empresa">
              @endif
                @csrf
                <div class="form-group">
                  <label for="exampleInputName2">TIPOS DE {{strtoupper($rota[$rota['rota']][0]->rota)}} </label>
                    <input name="tipo" type="text" class="form-control mr-2 ml-2" placeholder="" value="{{ $rota['edit']->tipo or old('tipo') }}" oninput="this.value = this.value.toUpperCase()">
                </div>
                <div class="form-group">
                  <button type="submit" class="btn btn-outline-success" name="submit" id="submit">
                    {{ isset($rota['edit'])?"Alterar":"Cadastrar"}}</button>
                </div>
              </form>
            </div>
            {{-- END FORM --}}
            {{-- START LIST --}}
            <div class="car-body">

              <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4 no-footer mt-3">

                <table class="table table-striped table-hover datatable dataTable no-footer table-sm" id="DataTables_Table_1" role="grid"
                aria-describedby="DataTables_Table_0_info" style="border-collapse: collapse !important">
                {{-- CAD TIPOS DE EMPRESAS --}}
                <thead>
                  <tr role="row">
                    <th class="sorting_asc" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Username: activate to sort column descending" style="width: 215px;">
                      Tipos de empresas
                    </th>
                    <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Date registered: activate to sort column ascending" style="width: 184px;">
                      Status
                    </th>
                    <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Role: activate to sort column ascending" style="width: 79px;">
                      Ação
                    </th>
                  </tr>
                </thead>
                {{-- LIST TIPOS DE EMPRESAS --}}
                <tbody>
                  @foreach ($rota[$rota['rota']] as $key)
                    <tr>
                      <td>{{ $key->adm_tipo }}</td>
                      <td>
                        <span class="badge badge-{{ $key->tipo=1?'success':'secondary' }}">
                          {{ $key->tipo=1?'ATIVO':'INATIVO' }}
                        </span>
                      </td>
                      <td>
                        <div class="row">
                          <div class="col-6">
                            <a href="{{route($rota['rota'].'.edit',$key->id_adm_tipo) }}" class="btn btn-block btn-outline-warning" title="Editar">
                              <i class="far fa-edit"></i>
                            </a>
                          </div>
                          <div class="col-6">
                            <form method="POST" action="{{route($rota['rota'].'.destroy',$key->id_adm_tipo) }}">
                              @csrf
                              @method('DELETE')
                              <button type="submit" class="btn btn-block btn-outline-danger" title="Excluir" onclick="return confirm('Confirma a exclusão?')">
                                <i class="far fa-trash-alt"></i>
                              </button>
                            </form>
                          </div>
                        </div>
                      </td>
                    </tr>
                  @endforeach
                </tbody>
              </table>
            </div>

          </div>
          {{-- END LIST --}}
        </div>

      </div>
    </div>
  </main>
@endsection

resources/views/ADM/empresateste.blade.php
@extends('layouts.sgs')

@section('content')
  @php
    $acl = $rota['acl'];
    $emp = $rota['empresa'];

    $emp->chunk(200, function($emp){
      foreach ($emp as $key) {
        echo $key->id_empresa;
      }
    });
    $cars=$rota['empresa'];
    $yes = array('this', 'is', 'an array');
    $rrr = "sdfsdgfsgsgfs";

 function isJson($string) {
   json_decode($string); return (json_last_error() == JSON_ERROR_NONE);
 }
 echo isJson($cars);
    // dd($emp);
    // foreach ($rota['empresa'] as $key) {
    //   echo $key->id_empresa;
    // }
  @endphp

  <main class="main">
    <br>
    <div class="container-fluid">
      <div class="row justify-content-center">
        <div class="col-md-12">
          @component('includes/alerts')
          @endcomponent

          <div class="card">
            <div class="card-header">
              @if (isset($rota['edit']))
                <form action="{{ route($rota['rota'].'.update',$rota['edit']['id_'.$rota['rota']]) }}" method="post" class="form-inline">
                  @method('PUT')
              @else
                <form action="{{ route('empresa.store')}}" method="post" class="form-inline">
              @endif
              @csrf

              <select class="form-control js-example-basic-single" name="state" onchange="location = this.value;">
                @foreach ($rota['empresa'] as $key)
                  <option value="{{route($rota['rota'].'.edit',$key['id_'.$rota['rota']]) }}">{{ $key->razao_social }}</option>
                @endforeach
              </select>

                <div class="form-group">
                  <label for="exampleInputName2">TESTE DE {{ strtoupper($rota['rota']) }} </label>
                  <div id="search-result"></div>
                    <input name="razao_social" type="text" class="form-control mr-2 ml-2" placeholder="" value="{{ $rota['edit']->razao_social or old('razao_social') }}">
                    <input name="empresa" type="text" class="form-control mr-2 ml-2" placeholder="" value="{{ $rota['edit']->empresa or old('empresa') }}">
                </div>
                <div class="form-group">
                  <button type="submit" class="btn btn-outline-success" id="submit">
                    {{ isset($rota['edit'])?"Alterar":"Cadastrar"}}</button>
                </div>

                <input type="hidden" name="id_tipo" value="1">
              </form>
            </div>
            <div class="car-body">

              <div class="">
                @foreach (range("A","Z") as $element)
                  <a href="#"></a>
                  {{ $element }}
                @endforeach
              </div>



          </div>
        </div>

      </div>
    </div>
  </main>
@endsection