routes/web.php
<?php
Route::get('/', function () { return view('auth/entrar'); });
Route::get('/login', function () { return view('auth/entrar'); });
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
// EXCEL
Route::get('import-export-view', 'ExcelController@importExportView')->name('import.export.view');
Route::post('import-file', 'ExcelController@importFile')->name('import.file');
Route::get('export-file/{type}', 'ExcelController@exportFile')->name('export.file');
// ROUTE ADM
Route::prefix('ADM')->group(function () {
  Route::resource('/adm_tipo', 'ADM\TipoC');
  Route::resource('/adm_item', 'ADM_ItemC');
  Route::post('/aprovaOrc/{id}', 'ADM\OrcamentoC@aprovaOrc')->name('aprovaOrc');
  Route::resource('/compra', 'ADM\CompraC');
  Route::resource('/g_link', 'ADM\G_LinkC');
  Route::resource('/link', 'ADM\LinkC');
  Route::resource('/orcamento', 'ADM\OrcamentoC');
  Route::resource('/pessoa', 'ADM\PessoaC');
  Route::resource('/ramo', 'EMP\RamoC');
});
//  ROUTE EMP
Route::prefix('EMP')->group(function () {
  Route::resource('/empresa', 'EMP\EmpresaC');
  Route::resource('/emp_tipo', 'EMP\TipoC');
  Route::resource('/inventario', 'EMP_InventarioC');
  Route::resource('/setor', 'EMP\SetorC');
  Route::resource('/emp_item', 'EMP_ItemC');
  Route::resource('/emp_emprestimo', 'EMP\EmprestimoC');
  Route::resource('/documento', 'TI\DocumentoC');
});
// ROUTE HRM
Route::prefix('HRM')->group(function () {
  Route::resource('/hrm_arq', 'TI\ArquivoC');
  Route::resource('/cargo', 'HRM\CargoC');
  Route::resource('/certificado', 'HRM\CertificadoC');
  Route::resource('/colaborador', 'HRM\ContratoC');
  Route::resource('/contrato', 'HRM\ContratoC');
  Route::resource('/curriculo', 'HRM\CurriculoC');
  Route::resource('/curso', 'HRM\CursoC');
  Route::resource('/exame', 'HRM\ExameC');
  Route::resource('/ferias', 'HRM\FeriasC');
  Route::resource('/ferias_pagto', 'HRM\Ferias_PagtoC');
  Route::resource('/hrm_tipo', 'HRM\TipoC');
  Route::resource('/dependente', 'HRM\DependenteC');
});
// ROUTE LOG - FROTA
Route::prefix('LOG')->group(function () {
  Route::resource('/abastecimento', 'LOG\AbastecimentoC');
  Route::resource('/documento', 'LOG\DocumentoC');
  Route::resource('/log_tipo', 'LOG\TipoC');
  Route::resource('/manutencao', 'LOG\ManutencaoC');
  Route::resource('/multa', 'LOG\MultaC');
  Route::resource('/ocorrencia', 'LOG\OcorrenciaC');
  Route::resource('/vei_seg', 'LOG\Vei_SegC');
  Route::resource('/veiculo', 'LOG\VeiculoC');
  Route::resource('/vistoria', 'LOG\VistoriaC');
});
// ROUTE LOG - MRP
Route::prefix('MRP')->group(function () {
  Route::post('/baixa_item', 'MRP\ItemC@baixa')->name('baixa_item');
  Route::resource('/emprestimo', 'MRP_EmprestimoC');
  Route::resource('/estoque', 'MRP\EstoqueC');
  Route::resource('/kit', 'MRP\KitC');
  Route::resource('/kit_item', 'MRP\Kit_ItemC');
  Route::resource('/movimento', 'MRP\MovimentoC');
  Route::post('/mrp_filtro', 'MRP\EstoqueC@mrp_filtro')->name('mrp_filtro');
  Route::resource('/mrp_item', 'MRP\ItemC');
  Route::resource('/mrp_tipo', 'MRP\TipoC');
  Route::resource('/pedido', 'MRP\PedidoC');
  Route::resource('/produto', 'MRP\ProdutoC');
  Route::get('/sts_pedido/{id}', 'MRP\PedidoC@status')->name('sts_pedido');
  Route::resource('/und', 'MRP\UndC');
});
// ROUTE TI
Route::prefix('TI')->group(function () {
  Route::resource('/help', 'TI\HelpC');
  Route::resource('/modulo', 'TI\ModuloC');
  Route::resource('/permissao', 'TI\AclC');
  Route::resource('/produtoENT', 'MRP_ProdutoEntC');
  Route::resource('/ti_tipo', 'TI\TipoC');
  Route::resource('/update', 'TI\UpdateC');
  Route::resource('/usuario', 'TI\UsuarioC');
});

/*
GET       /photos	               index	   photos.index
GET	      /photos/create	       create	   photos.create
POST	    /photos	               store	   photos.store
GET	      /photos/{photo}	       show	     photos.show
GET	      /photos/{photo}/edit   edit	     photos.edit
PUT/PATCH	/photos/{photo}        update	   photos.update
DELETE	  /photos/{photo}	       destroy	 photos.destroy
*/

app/Models/EMP/EmpresaM.php
<?php namespace App\Models\EMP;

use Illuminate\Database\Eloquent\Model;

class EmpresaM extends Model
{
  protected $table = 'emp_empresas';
  protected $primaryKey = 'id_empresa';

  protected $fillable = [
    'id_empresa',
    'empresa',
    'created_at',
    'updated_at',
    'sts_empresa',
    'razao_social',
    'observacoes',
    'data_cadastro',
    'natureza_juridica',
    'tipo',
    'faturamento',
    'faixa_funcionario',
    'porte',
    'tempo_mercado',
    'ie',
    'site',
    'cnpj',
    'id_tipo'
  ];

  public function tipos()    {
    return $this->hasMany(TipoM::class);
  }

  public function ramos()    {
    return $this->hasMany(RamoM::class,'id_ramo','id_ramo');
  }

  public function ramos_emp()    {
    return $this->belongsToMany(Ramo_EmpM::class,'id_empresa','id_empresa');
  }
}

app/Models/EMP/Modulo_RamoM.php
<?php namespace App\Models\EMP;

use Illuminate\Database\Eloquent\Model;

class Modulo_RamoM extends Model
{
  protected $table = 'emp_modulos_ramos';
  protected $primaryKey = 'id_ramo';
  protected $fillable = [
    'id_modulo',
    'id_ramo'
  ];
}

app/Models/EMP/RamoM.php
<?php namespace App\Models\EMP;

use Illuminate\Database\Eloquent\Model;

class RamoM extends Model
{
  protected $table = 'emp_ramos';
  protected $primaryKey = 'id_ramo';

  protected $fillable = [
    'id_ramo',
    'ramo',
    'sts_ramo',
    'updated_at',
    'created_at',
    'rota',
    'desc'
  ];

  public function modulosramos()    {
    return $this->hasMany(Modulo_RamoM::class,'id_ramo','id_ramo');
  }
}

app/Models/EMP/Ramo_EmpM.php
<?php namespace App\Models\EMP;

use Illuminate\Database\Eloquent\Model;

class Ramo_EmpM extends Model
{
  protected $table = 'emp_ramo_emp';
  protected $primaryKey = 'id_ramo_emp';

  protected $fillable = [
    'id_ramo_emp',
    'id_ramo',
    'id_empresa',
    'created_at',
    'updated_at',
    'sts_ramo_emp'
  ];

  public function empresas()    {
    return $this->hasOne(EmpresaM::class,'id_empresa','id_empresa');
  }
  // public function atendente()    {
  //   return $this->hasOne('\App\User','id','id_atendente');
  // }
}

app/Http/Controllers/EMP/EmpresaC.php
<?php namespace App\Http\Controllers\EMP;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\EMP\EmpresaM;
use App\Models\EMP\Ramo_EmpM;
use App\Models\EMP\TipoM;
use App\Models\EMP\RamoM;

class EmpresaC extends Controller
{
  public $rota = ['rota' => 'empresa'];

  public function carrega($letra = "0")  {
    $this->rota = TI_acl(H_lead($this->rota));

    $this->rota['tipos'] = TipoM::where('sts_tipo','=',1)->orderby('tipo')->get();
    $this->rota['ramos'] = RamoM::where('sts_ramo','=',1)->orderby('ramo')->get();
    $this->rota[$this->rota['rota']] = EmpresaM::select('id_empresa','empresa','razao_social')
                              ->where('sts_empresa','=',1)
                              ->where('razao_social','LIKE',$letra.'%')
                              ->orderby('razao_social')->get();
  }

  public function index(Request $req)  {
    $this->carrega();
    if (isset($req['campo'])) {
      if($req['campo'] == 'id_empresa')
        return redirect()->route($this->rota['rota'].'.edit',$req['search']);
      if($req['campo'] == 'cnpj'){
        $id = EmpresaM::where('cnpj',$req['search'])->get();
        if($id->count() == 0)
          return redirect()->back()->with(['danger' => 'CNPJ não encontrado.']);
        return redirect()->route($this->rota['rota'].'.edit',$id->id_empresa);
      }
    }
    return view('adm.'.$this->rota['rota'], ['rota'=>$this->rota]);
  }

  public function show($letra)  {
    $this->carrega($letra);
    // return view('adm.empresa', ['rota'=>$this->rota]);
    return view('adm.'.$this->rota['rota'], ['rota'=>$this->rota]);
  }

  public function store(Request $request, EmpresaM $id)  {
    $data = $request->all();
    $idE = $id->create($data);

    foreach ($data['id_ramo'] as $key) {
      $idEM = new Ramo_EmpM;
      $idEM->id_empresa = $idE->id_empresa;
      $idEM->id_ramo = $key;
      $idEM->save();
    }
    return redirect()->back()->with(['success' => 'Cadastrado com sucesso.']);
  }

  public function edit($id)  {
    $this->carrega();
    if($this->rota['acl']->u == 0) return redirect()->back()->with(['danger' => 'Sem acesso.']);
    $this->rota['edit']       = EmpresaM::findOrFail($id);
    $this->rota['ramos_emp']  = Ramo_EmpM::where('id_empresa',$id)->get();

    return view('adm.'.$this->rota['rota'], ['rota'=>$this->rota]);
  }

  public function update(Request $request, $id)  {
    $data = $request->all();
    Ramo_EmpM::where('id_empresa', $id)->delete();
    foreach ($data['id_ramo'] as $key) {
      if ($key > 0) {
        $idEM = Ramo_EmpM::firstOrNew(['id_empresa'=>$id,'id_ramo'=>$key]);
        $idEM->id_empresa = $id;
        $idEM->id_ramo = $key;
        $idEM->save();
      }
    }
    $id = EmpresaM::findOrFail($id);
    $id->update($data);

    return redirect()->route($this->rota['rota'].'.index')->with(['success' => $this->rota['rota'].' alterado com sucesso.']);
  }

  public function destroy($id)  {
    $id = EmpresaM::findOrFail($id);
    $id->update(['sts_'.$this->rota['rota'] => 0]);

    return redirect()->route($this->rota['rota'].'.index')->with(['success' => $this->rota['rota'].' excluído com sucesso.']);
  }
}

app/Http/Controllers/EMP/EmprestimoC.php
<?php namespace App\Http\Controllers\EMP;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\EMP_EmprestimoM;
use App\Models\EMP_ItemM;

class EmprestimoC extends Controller
{
  public $rota = ['rota' => 'emp_emprestimo','pasta'=>'EMP/EMPRE/'];

  public function carrega()  {
    $this->rota[$this->rota['rota']] = EMP_EmprestimoM::where('sts_'.$this->rota['rota'],'>',0)->get();
    $this->rota = H_rota($this->rota);
    $this->rota = H_colaborador($this->rota);
  }

  public function index()  {
    TI_sgs_log($this->rota['rota'],'index'); // REG_LOG
    $this->carrega();
    $this->rota['itens'] = EMP_ItemM::where('sts_emp_item',1)->get();

    return view('EMP.'.$this->rota['rota'], ['rota'=>$this->rota]);
  }
  public function show($id){
    $this->rota['print'] = EMP_EmprestimoM::findOrFail($id);

    return view('PRINT.'.$this->rota['rota'], ['rota'=>$this->rota]);
  }

  public function store(Request $request, EMP_EmprestimoM $id)  {
    $data = $request->all();

    $log = $id->create($data);
    $idE = EMP_ItemM::findOrFail($data['id_item']);
    $idE->update(['sts_emp_item' => 2]);

    if($request->arquivo)
      $data['arquivo'] = TI_up_file($request, $this->rota['pasta'].$idV->placa.'/', $idT->documento);

    TI_sgs_log($this->rota['rota'],'store',$log['id_'.$this->rota['rota']]); // REG_LOG

    return redirect()->route($this->rota['rota'].'.show',$log['id_'.$this->rota['rota']]);
    // return redirect()->back()->with(['success' => 'Cadastrado com sucesso.']);
  }

  public function edit($id)  {
    $this->carrega();
    if($this->rota['acl']->u == 0) return redirect()->back()->with(['danger' => 'Sem acesso.']);
    $this->rota['edit'] = EMP_EmprestimoM::findOrFail($id);
    $this->rota['itens'] = EMP_ItemM::where('sts_emp_item','>',0)->get();

    return view('EMP.'.$this->rota['rota'], ['rota'=>$this->rota]);
  }

  public function update(Request $request, $id)  {
    $data = $request->all();
    if($request->arquivo)
      $data['arquivo'] = TI_up_file($request, $this->rota['pasta'].$idV->placa.'/', $idT->tipo);

    $idUP = EMP_EmprestimoM::findOrFail($id);
    TI_sgs_log($this->rota['rota'],'update',$id,$idUP); // REG_LOG

    if(isset($data['fim'])){
      $idE = EMP_ItemM::findOrFail($data['id_item']);
      $idE->update(['sts_emp_item' => 1]);
      $data['sts_emp_emprestimo'] = 2;
    }else {
      $idE = EMP_ItemM::findOrFail($data['id_item']);
      $idE->update(['sts_emp_item' => 2]);
      $data['sts_emp_emprestimo'] = 1;
    }

    $idUP->update($data);
    return redirect()->route($this->rota['rota'].'.index')->with(['success' => $this->rota['rota'].' alterado com sucesso.']);
  }

  public function destroy($id)  {
    TI_sgs_log($this->rota['rota'],'destroy',$id); // REG_LOG
    $id = EMP_EmprestimoM::findOrFail($id);
    $id->update(['sts_'.$this->rota['rota'] => 0]);

    return redirect()->route($this->rota['rota'].'.index')->with(['success' => $this->rota['rota'].' excluído com sucesso.']);
  }
}

app/Http/Controllers/EMP/RamoC.php
<?php namespace App\Http\Controllers\EMP;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\EMP\RamoM;
use App\Models\EMP\Modulo_RamoM;

class RamoC extends Controller
{
  public $rota = ['rota' => 'ramo'];

  public function carrega()  {
    $this->rota = TI_acl(TI_modulo($this->rota));
    $this->rota[$this->rota['rota']] = RamoM::where('sts_'.$this->rota['rota'],'>',0)->get();
  }

  public function index()  {
    $this->carrega();

    return view('adm.'.$this->rota['rota'], ['rota' => $this->rota]);
  }

  public function show($id)  {
    $this->rota[$this->rota['rota']] = RamoM::where('sts_tipo','>',0)
             ->where('tabela',$id)->get();

    return view('adm.'.$this->rota['rota'], ['rota' => $this->rota]);
  }

  public function store(Request $request, RamoM $id)  {
    $data = $request->all();
    $idR = $id->create($data);

    foreach ($data['id_modulo'] as $key) {
      $idM = new Modulo_RamoM;
      $idM->id_modulo = $key;
      $idM->id_ramo = $idR->id_ramo;
      $idM->save();
    }


    return redirect()->back()->with(['success' => 'Cadastrado com sucesso.']);
  }

  public function edit($id)  {
    $this->carrega();
    if($this->rota['acl']->u == 0) return redirect()->back()->with(['danger' => 'Sem acesso.']);
    $this->rota['edit'] = RamoM::findOrFail($id);

    return view('adm.'.$this->rota['rota'], ['rota' => $this->rota]);
  }

  public function update(Request $request, $id)  {
    $for = $request->all();
    Modulo_RamoM::where('id_ramo', $id)->delete();
    foreach ($for['id_modulo'] as $key) {
      $idM = Modulo_RamoM::firstOrCreate(['id_modulo'=>$key,'id_ramo'=>$id]);
    }
    $idM->save();

    $id = RamoM::findOrFail($id);
    $id->update($request->all());

    return redirect()->route($this->rota['rota'].'.index')->with(['success' => 'Alterado com sucesso.']);
  }

  public function destroy($id)  {
    $id = RamoM::findOrFail($id);
    $id->update(['sts_tipo' => 0]);

    return redirect()->route($this->rota['rota'].'.index')->with(['success' => 'Excluido com sucesso.']);
  }
}

app/Http/Controllers/EMP/SetorC.php
<?php namespace App\Http\Controllers\EMP;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\EMP\SetorM;

class SetorC extends Controller
{
  public $rota = ['rota' => 'setor'];

  public function carrega()  {
    $this->rota[$this->rota['rota']] = SetorM::where('sts_'.$this->rota['rota'],'>',0)->get();
    $this->rota = TI_acl($this->rota);
    $this->rota = H_emp_gru($this->rota);
  }

  public function index()  {
    TI_sgs_log($this->rota['rota'],'index'); // REG_LOG
    $this->carrega();

    return view('EMP.'.$this->rota['rota'], ['rota'=>$this->rota]);
  }

  public function store(Request $request, SetorM $id)  {
    $data = $request->all();

    $log = $id->create($data);
    TI_sgs_log($this->rota['rota'],'store',$log['id_'.$this->rota['rota']]); // REG_LOG

    return redirect()->back()->with(['success' => 'Cadastrado com sucesso.']);
  }

  public function edit($id)  {
    $this->carrega();
    if($this->rota['acl']->u == 0) return redirect()->back()->with(['danger' => 'Sem acesso.']);
    $this->rota['edit'] = SetorM::findOrFail($id);

    return view('EMP.'.$this->rota['rota'], ['rota'=>$this->rota]);
  }

  public function update(Request $request, $id)  {
    $data = $request->all();

    $idUP = SetorM::findOrFail($id);
    TI_sgs_log($this->rota['rota'],'update',$id,$idUP); // REG_LOG
    $idUP->update($request->all());

    return redirect()->route($this->rota['rota'].'.index')->with(['success' => $this->rota['rota'].' alterado com sucesso.']);
  }

  public function destroy($id)  {
    TI_sgs_log($this->rota['rota'],'destroy',$id); // REG_LOG
    $id = SetorM::findOrFail($id);
    $id->update(['sts_'.$this->rota['rota'] => 0]);

    return redirect()->route($this->rota['rota'].'.index')->with(['success' => $this->rota['rota'].' excluído com sucesso.']);
  }
}

app/Http/Controllers/EMP/TipoC.php
<?php namespace App\Http\Controllers\EMP;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\G_linkM;
use App\Models\TI\VersaoM;
use App\Models\EMP\TipoM;

class TipoC extends Controller
{
  public $rota = ['rota' => 'emp_tipo'];

  public function index()  {
    $this->rota[$this->rota['rota']] = TipoM::where('sts_tipo','>',0)->get();

    return view('emp.emp_tipo', ['rota' => $this->rota]);
  }

  public function show($id)  {
    $this->rota[$this->rota['rota']] =
    TipoM::where('sts_tipo','>',0)
             ->where('tabela',$id)->get();

    return view('emp.emp_tipo', ['rota' => $this->rota]);
  }

  public function store(Request $request, TipoM $id)  {
    $id->create($request->all());

    return redirect()->back()->with(['success' => 'Cadastrado com sucesso.']);
  }

  public function edit($id)  {
    $this->rota[$this->rota['rota']] = TipoM::all();
    $this->rota['edit'] = TipoM::findOrFail($id);

    return view('emp.emp_tipo', ['rota' => $this->rota]);
  }

  public function update(Request $request, $id)  {
    $id = TipoM::findOrFail($id);
    $id->update($request->all());

    return redirect()->route('emp_tipo.index')->with(['success' => 'Alterado com sucesso.']);
  }

  public function destroy($id)  {
    $id   = TipoM::findOrFail($id);
    $id->update(['sts_tipo' => 0]);

    return redirect()->route('emp_tipo.index')->with(['success' => 'Excluido com sucesso.']);
  }
}

resources/views/EMP/inventario.blade.php
@extends('layouts.sgs')

@section('content')
  @php
  $idV = $idM = $idF = 0;
  $idS = 1;
  $acl = $rota['acl'];
  if(isset($rota['edit'])){
    $idS = $rota['edit']->sts_solicitacao;
  }
  @endphp
  <main class="main">
    <br>
    <div class="container-fluid">
      <div class="row justify-content-center">
        <div class="col-md-12">

          @component('includes/alerts')
          @endcomponent

          <div class="card">
            {{-- FORM CADASTRO --}}
            <div class="card-header">
              @if (isset($rota['edit']))
                <form action="{{ route($rota['rota'].'.update',$rota['edit']['id_'.$rota['rota']]) }}" method="post" class="form" enctype="multipart/form-data">
                  @method('PUT')
                @else
                  <form action="{{ route($rota['rota'].'.store') }}" method="post" class="form" enctype="multipart/form-data">
                    <input type="hidden" name="id_colaborador" value="{{ Auth::user()->id }}">
                  @endif
                  @csrf
                  <div class="row justify-content-between">
                    <div class="col-8">
                      <div class="form-group">
                        <label for="exampleInputName2">INVENTÁRIO</label>
                      </div>
                    </div>
                    {{-- ACL FORM CAD --}}
                    <div class="col-1">
                      @if ($acl->c == 1)
                        <button id="btn-plus" type="button" class="btn btn-pill btn-outline-success ml-3" onclick="Mudarestado('div-cad-{{$rota['rota']}}')">
                          <i class='fa fa-plus'></i>
                        </button>
                      @endif
                    </div>
                    {{-- ACL FORM CAD --}}
                  </div>

                  <div id="div-cad-{{$rota['rota']}}" class="{{isset($rota['edit'])?'divOpen':'divClose'}}">
                    <div class="row">

                      <div class="col-5">
                        <div class="input-group">
                          <div class="input-group-prepend">
                            <span class="input-group-text">Empresas</span>
                          </div>
                          <select id="select1" name="id_empresa" class="form-control">
                            <option>Selecione ...</option>
                            @foreach ($rota['empresas'] as $key)
                              <option value="{{ $key->id_empresa }}" {{ $key->id_empresa==$idF?"selected":"" }}>
                                {{ $key->empresa }}
                              </option>
                            @endforeach
                          </select>
                        </div>
                      </div>

                      <div class="col-5">
                        <div class="input-group">
                          <div class="input-group-prepend">
                            <span class="input-group-text">Inventário</span>
                          </div>
                          <input type="text" name="inventario" class="form-control" oninput="this.value = this.value.toUpperCase()" value="{{ $rota['edit']->inventario or old('inventario') }}">
                        </div>

                      </div>
                      <div class="col-2">
                        <button type="submit" class="btn btn-outline-success btn-block" id="submit">
                          {{ isset($rota['edit'])?"Salvar":"Cadastrar"}}
                        </button>
                      </div>
                    </div>
                  </div>

                </form>
              </div>

              <div class="car-body">
                {{-- DATATABLE --}}
                <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper  dt-bootstrap4 no-footer mt-3">

                  <table class="table table-striped table-hover datatable dataTable no-footer table-sm" id="DataTables_Table_1" role="grid"
                  aria-describedby="DataTables_Table_0_info" style="border-collapse: collapse !important">
                  <thead>
                    <tr role="row">
                      <th class="sorting_asc" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Username: activate to sort column descending" style="width: 215px;">
                        Inventários
                      </th>
                      <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Role: activate to sort column ascending" style="width: 79px;">
                        Ação
                      </th>
                    </tr>
                  </thead>
                  {{-- LIST --}}
                  <tbody>
                    @foreach ($rota[$rota['rota']] as $key)
                      <tr>
                        <td>
                          {{ $key[$rota['rota']] }}
                        </div>
                      </td>
                      <td>
                        {{-- ACL ACOES TABLE --}}
                        <div class="row">
                        <div class="">
                          <a href="{{route('emp_item.show',$key->id_inventario) }}" class="btn btn-block btn-ghost-info" title="Abrir {{ $key[$rota['rota']] }}">
                            <i class="fas fa-toolbox"></i>
                          </a>
                        </div>
                          @if (isset($key->arquivo))
                            @if ($acl->dw == 1)
                              <div class="">
                                <a href="{{ asset('storage/'.$rota['pasta'].$key->arquivo)}}" target="new" title="{{$key->arquivo}}" class="btn btn-block btn-ghost-success">
                                  <i class="far fa-file-pdf"></i>
                                </a>
                              </div>
                            @else
                              <div class="btn text-secondary"><i class="far fa-file-pdf"></i></div>
                            @endif
                          @else
                            <div class="btn text-dark"><i class="fas fa-ban"></i></div>
                          @endif

                          @if ($acl->u == 1)
                            <div class="">
                              <a href="{{route($rota['rota'].'.edit',$key['id_'.$rota['rota']]) }}" class="btn btn-block btn-ghost-warning" title="Editar">
                                <i class="far fa-edit"></i>
                              </a>
                            </div>
                          @else
                            <div class="btn text-secondary"><i class="far fa-edit"></i></div>
                          @endif

                          @if ($acl->d == 1)
                            <div class="">
                              <form method="POST" action="{{route($rota['rota'].'.destroy',$key['id_'.$rota['rota']]) }}">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-block btn-ghost-danger" title="Excluir" onclick="return confirm('Confirma a exclusão?')">
                                  <i class="far fa-trash-alt"></i>
                                </button>
                              </form>
                            </div>
                          @else
                            <div class="btn text-secondary"><i class="far fa-trash-alt"></i></div>
                          @endif
                        </div>
                        {{-- ACL ACOES TABLE --}}
                      </td>
                    </tr>
                  @endforeach
                </tbody>
              </table>
            </div>

          </div>
        </div>

      </div>
    </div>
  </main>
@endsection