routes/web.php
<?php
Route::get('/', function () { return view('auth/entrar'); });
Route::get('/login', function () { return view('auth/entrar'); });
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
// EXCEL
Route::get('import-export-view', 'ExcelController@importExportView')->name('import.export.view');
Route::post('import-file', 'ExcelController@importFile')->name('import.file');
Route::get('export-file/{type}', 'ExcelController@exportFile')->name('export.file');
// ROUTE ADM
Route::prefix('ADM')->group(function () {
  Route::resource('/adm_tipo', 'ADM\TipoC');
  Route::resource('/adm_item', 'ADM_ItemC');
  Route::post('/aprovaOrc/{id}', 'ADM\OrcamentoC@aprovaOrc')->name('aprovaOrc');
  Route::resource('/compra', 'ADM\CompraC');
  Route::resource('/g_link', 'ADM\G_LinkC');
  Route::resource('/link', 'ADM\LinkC');
  Route::resource('/orcamento', 'ADM\OrcamentoC');
  Route::resource('/pessoa', 'ADM\PessoaC');
  Route::resource('/ramo', 'EMP\RamoC');
});
//  ROUTE EMP
Route::prefix('EMP')->group(function () {
  Route::resource('/empresa', 'EMP\EmpresaC');
  Route::resource('/emp_tipo', 'EMP\TipoC');
  Route::resource('/inventario', 'EMP_InventarioC');
  Route::resource('/setor', 'EMP\SetorC');
  Route::resource('/emp_item', 'EMP_ItemC');
  Route::resource('/emp_emprestimo', 'EMP\EmprestimoC');
  Route::resource('/documento', 'TI\DocumentoC');
});
// ROUTE HRM
Route::prefix('HRM')->group(function () {
  Route::resource('/hrm_arq', 'TI\ArquivoC');
  Route::resource('/cargo', 'HRM\CargoC');
  Route::resource('/certificado', 'HRM\CertificadoC');
  Route::resource('/colaborador', 'HRM\ContratoC');
  Route::resource('/contrato', 'HRM\ContratoC');
  Route::resource('/curriculo', 'HRM\CurriculoC');
  Route::resource('/curso', 'HRM\CursoC');
  Route::resource('/exame', 'HRM\ExameC');
  Route::resource('/ferias', 'HRM\FeriasC');
  Route::resource('/ferias_pagto', 'HRM\Ferias_PagtoC');
  Route::resource('/hrm_tipo', 'HRM\TipoC');
  Route::resource('/dependente', 'HRM\DependenteC');
});
// ROUTE LOG - FROTA
Route::prefix('LOG')->group(function () {
  Route::resource('/abastecimento', 'LOG\AbastecimentoC');
  Route::resource('/documento', 'LOG\DocumentoC');
  Route::resource('/log_tipo', 'LOG\TipoC');
  Route::resource('/manutencao', 'LOG\ManutencaoC');
  Route::resource('/multa', 'LOG\MultaC');
  Route::resource('/ocorrencia', 'LOG\OcorrenciaC');
  Route::resource('/vei_seg', 'LOG\Vei_SegC');
  Route::resource('/veiculo', 'LOG\VeiculoC');
  Route::resource('/vistoria', 'LOG\VistoriaC');
});
// ROUTE LOG - MRP
Route::prefix('MRP')->group(function () {
  Route::post('/baixa_item', 'MRP\ItemC@baixa')->name('baixa_item');
  Route::resource('/emprestimo', 'MRP_EmprestimoC');
  Route::resource('/estoque', 'MRP\EstoqueC');
  Route::resource('/kit', 'MRP\KitC');
  Route::resource('/kit_item', 'MRP\Kit_ItemC');
  Route::resource('/movimento', 'MRP\MovimentoC');
  Route::post('/mrp_filtro', 'MRP\EstoqueC@mrp_filtro')->name('mrp_filtro');
  Route::resource('/mrp_item', 'MRP\ItemC');
  Route::resource('/mrp_tipo', 'MRP\TipoC');
  Route::resource('/pedido', 'MRP\PedidoC');
  Route::resource('/produto', 'MRP\ProdutoC');
  Route::get('/sts_pedido/{id}', 'MRP\PedidoC@status')->name('sts_pedido');
  Route::resource('/und', 'MRP\UndC');
});
// ROUTE TI
Route::prefix('TI')->group(function () {
  Route::resource('/help', 'TI\HelpC');
  Route::resource('/modulo', 'TI\ModuloC');
  Route::resource('/permissao', 'TI\AclC');
  Route::resource('/produtoENT', 'MRP_ProdutoEntC');
  Route::resource('/ti_tipo', 'TI\TipoC');
  Route::resource('/update', 'TI\UpdateC');
  Route::resource('/usuario', 'TI\UsuarioC');
});

/*
GET       /photos	               index	   photos.index
GET	      /photos/create	       create	   photos.create
POST	    /photos	               store	   photos.store
GET	      /photos/{photo}	       show	     photos.show
GET	      /photos/{photo}/edit   edit	     photos.edit
PUT/PATCH	/photos/{photo}        update	   photos.update
DELETE	  /photos/{photo}	       destroy	 photos.destroy
*/

app/Models/MRP/EstoqueM.php
<?php namespace App\Models\MRP;

use Illuminate\Database\Eloquent\Model;
use App\Models\ADM\PessoaM;
use App\Models\EMP\EmpresaM;

class EstoqueM extends Model
{
  protected $table = 'mrp_estoques';
  protected $primaryKey = 'id_estoque';

  protected $fillable = [
    'id_estoque',
    'id_empresa',
    'id_almoxarife',
    'id_endereco',
    'id_mrp_tipo',
    'estoque',
    'created_at',
    'updated_at',
    'sts_estoque'
  ];

  public function pessoas()    {
    return $this->hasOne(PessoaM::class,'id_pessoa','id_almoxarife');
  }

  public function tipos()    {
    return $this->hasOne(TipoM::class,'id_mrp_tipo','id_mrp_tipo');
  }

  public function empresas()    {
    return $this->hasOne(EmpresaM::class,'id_empresa','id_empresa');
  }
}

app/Models/MRP/KitM.php
<?php namespace App\Models\MRP;

use Illuminate\Database\Eloquent\Model;

class KitM extends Model
{
  protected $table = 'mrp_kits';
  protected $primaryKey = 'id_kit';

  protected $fillable = [
    'id_kit',
    'kit',
    'updated_at',
    'created_at',
    'sts_kit'
  ];
}

app/Models/MRP/UndM.php
<?php namespace App\Models\MRP;

use Illuminate\Database\Eloquent\Model;

class UndM extends Model
{
  protected $table = 'mrp_unds';
  protected $primaryKey = 'id_und';

  protected $fillable = [
    'id_und',
    'und',
    'cod',
    'sts_und',
    'updated_at',
    'created_at'
  ];
}

app/Http/Controllers/MRP/EstoqueC.php
<?php namespace App\Http\Controllers\MRP;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\MRP\EstoqueM;
use App\Models\MRP\ItemM;

class EstoqueC extends Controller
{
  public $rota = ['rota' => 'estoque','pasta'=>'MRP/EST/'];

  public function carrega()  {
    $this->rota = TI_acl(H_colaborador(H_emp_gru(H_mrp_tipo($this->rota,43))));
    $this->rota[$this->rota['rota']] = EstoqueM::where('sts_'.$this->rota['rota'],'>',0)->get();
  }

  public function index()  {
    unset($_SESSION['search']);
    TI_sgs_log($this->rota['rota'],'index'); // REG_LOG
    $this->carrega();

    return view('MRP.'.$this->rota['rota'], ['rota'=>$this->rota]);
  }

  public function show($id,Request $req, ItemM $item)  { //dd($req->all());
    TI_sgs_log($this->rota['rota'],'index'); // REG_LOG
    $this->rota = MRP_item_estoque($this->rota, $id);

    if(isset($req) and $req->query('act') == 'print'){
      if(isset($_SESSION['search'])){
        $this->rota['item'] = $item->search($_SESSION['search']);
        return view('PRINT.estoque', ['rota'=>$this->rota]);
      }
      return view('PRINT.estoque', ['rota'=>$this->rota]);
    }

    $this->carrega();

    return view('MRP.item_estoque', ['rota'=>$this->rota]);
  }

  public function mrp_filtro(Request $req, ItemM $item)  {
    $data = $req->all();
    unset($_SESSION['search']);
    $this->carrega();

    $this->rota = MRP_item_estoque($this->rota, $req['id_estoque']);

    $this->rota['item'] = $item->search($data);

    unset($data['_token']);
    $_SESSION['search'] = $data;

    return view('MRP.item_estoque', ['rota'=>$this->rota]);
  }

  public function store(Request $request, EstoqueM $id)  {
    $data = $request->all();

    $log = $id->create($data);
    TI_sgs_log($this->rota['rota'],'store',$log['id_'.$this->rota['rota']]); // REG_LOG

    return redirect()->back()->with(['success' => 'Cadastrado com sucesso.']);
  }

  public function edit($id)  {
    $this->carrega();
    if($this->rota['acl']->u == 0) return redirect()->back()->with(['danger' => 'Sem acesso.']);
    $this->rota['edit'] = EstoqueM::findOrFail($id);

    return view('MRP.'.$this->rota['rota'], ['rota'=>$this->rota]);
  }

  public function update(Request $request, $id)  {
    $data = $request->all();

    $idUP = EstoqueM::findOrFail($id);
    TI_sgs_log($this->rota['rota'],'update',$id,$idUP); // REG_LOG
    $idUP->update($request->all());

    return redirect()->route($this->rota['rota'].'.index')->with(['success' => $this->rota['rota'].' alterado com sucesso.']);
  }

  public function destroy($id)  {
    TI_sgs_log($this->rota['rota'],'destroy',$id); // REG_LOG
    $id = EstoqueM::findOrFail($id);
    $id->update(['sts_'.$this->rota['rota'] => 0]);

    return redirect()->route($this->rota['rota'].'.index')->with(['success' => $this->rota['rota'].' excluído com sucesso.']);
  }
}

app/Http/Controllers/MRP/ItemC.php
<?php namespace App\Http\Controllers\MRP;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\MRP\ItemM;
use App\Models\MRP\MovimentoM;
use App\Models\MRP\PedidoM;

class ItemC extends Controller
{
  public $rota = ['rota' => 'mrp_item'];

  public function carrega($id,$aux)  {
    $this->rota = TI_acl(H_est(H_prod($this->rota)));

    $this->rota['input'] = ['id'=>$id,'rota'=>$aux];
    $this->rota[$this->rota['rota']] = ItemM::where('sts_'.$this->rota['rota'],'>',0)
                                     ->where('id_'.$aux,$id)->get();
    $this->rota['MRP_item_estoque'] = ItemM::whereNotNull('id_estoque')->get();
  }

  public function show($id,Request $request)  {
    $this->rota['pedido'] = PedidoM::findOrFail($id);
    TI_sgs_log($this->rota['rota'],'index'); // REG_LOG
    $this->carrega($id,$request->query('rota'));
    TI_view_fluxo($this->rota['rota'],$id);

    if($this->rota['pedido']->sts_pedido == 3){ // PRINT
      $ret = MRP_up_sts_pedido($id);
      TI_sgs_log('pedido','status',$id,$ret['OLD']); // REG_LOG {ROTA|METODO|ID|OLD}
      return view('PRINT.pedido', ['rota'=>$this->rota]);
    }elseif ($request->query('act') == 'print') {
      return view('PRINT.pedido', ['rota'=>$this->rota]);
    }

    return view('MRP.'.$this->rota['rota'], ['rota'=>$this->rota]);
  }

  public function store(Request $request)  {
    $data = $request->all();
    $id = ItemM::firstOrNew(['id_produto'=>$data['id_produto'],'id_pedido'=>$data['id_pedido']]);
    $id->qnt = $id->qnt + $data['qnt'];

    if(isset($data['id_pedido'])) MRP_up_total_pedido($data['id_pedido'],$id->qnt);

    $id->save($data);
    TI_sgs_log($this->rota['rota'],'store',$id['id_'.$this->rota['rota']]); // REG_LOG

    return redirect()->back()->with(['success' => 'Cadastrado com sucesso.']);
  }

  public function edit($id)  {
    $this->rota['edit'] = ItemM::findOrFail($id);
    $this->carrega($this->rota['edit']['id_'.$this->rota['edit']->rota],$this->rota['edit']->rota);
    if($this->rota['acl']->u == 0) return redirect()->back()->with(['danger' => 'Sem acesso.']);

  if($this->rota['edit']->id_pedido != null){
    if($this->rota['edit']->pedidos->sts_pedido == 1)
    return view('MRP.'.$this->rota['rota'], ['rota'=>$this->rota]);
  }
  return view('MRP.'.$this->rota['rota'], ['rota'=>$this->rota]);

    return redirect()->back()->with(['Danger' => 'Acesso negado.']);
  }

  public function baixa(Request $request){
    $data = $request->all();
    $y = 0;
    foreach ($data['id_mrp_item'] as $key) {
      if($data['id_estoque'][$y] > 0 and $data['qnt'][$y] > $data['atendido'][$y]){
        $atEst['id_mrp_tipo'] = 5; // 5 baixa estoque
        $atEst['id_produto'] = $data['id_produto'][$y];
        $atEst['id_estoque'] = $data['id_estoque'][$y];
        $atEst['id_pedido']  = $data['id_pedido'][$y];
        $atEst['qnt'] = $data['qnt'][$y] - $data['atendido'][$y];
        $idEst = MRP_up_estoque($atEst);

        $idI = ItemM::findOrFail($key);
        $idI->atendido = $idI->atendido + $idEst;
        $idI->save();

        MRP_up_ped_atendido($data['id_pedido'],$idEst);

        $idM = new MovimentoM;
        $idM->id_produto  = $atEst['id_produto'];
        $idM->id_estoque  = $atEst['id_estoque'];
        $idM->id_pedido   = $data['id_pedido'];
        $idM->id_user     = \Auth::user()->id;
        $idM->id_mrp_tipo = 5;
        $idM->qnt         = $atEst['qnt'];
        $idM->save();
      }

      $y++;
    }
    return redirect()->back()->with(['success' => 'Cadastrado com sucesso.']);
  }

  public function update(Request $request, $id)  {
    $data = $request->all();

    if(isset($data['add'])){
      $id = new ItemM;
      $log = $id->create($data);
      TI_sgs_log($this->rota['rota'],'store',$log['id_'.$this->rota['rota']]); // REG_LOG
      return redirect()->back()->with(['success' => 'Cadastrado com sucesso.']);
    }else {
      $idUP = ItemM::findOrFail($id);
      $idUP->update($request->all());
      TI_sgs_log($this->rota['rota'],'update',$id,$idUP); // REG_LOG
      return redirect()->back()->with(['success' => 'Alterado com sucesso.']);
    }
    return redirect()->back()->with(['danger' => 'Erro na requisição.']);
  }

  public function destroy($id)  {
    TI_sgs_log($this->rota['rota'],'destroy',$id); // REG_LOG
    $id = ItemM::findOrFail($id);
    $id->update(['sts_'.$this->rota['rota'] => 0]);

    return redirect()->back()->with(['success' => $this->rota['rota'].' excluído com sucesso.']);
  }
}

app/Http/Controllers/MRP/MovimentoC.php
<?php namespace App\Http\Controllers\MRP;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\HRM\ColaboradorM;
use App\Models\MRP\MovimentoM;

class MovimentoC extends Controller
{
  public $rota = ['rota' => 'movimento','pasta'=>'MRP/MOV/'];

  public function carrega()  {
    $this->rota = TI_acl(H_est(H_prod(H_mrp_tipo($this->rota,36))));

    $this->rota[$this->rota['rota']] = MovimentoM::where('sts_'.$this->rota['rota'],'>',0)->get();
    $this->rota['colaborador'] = ColaboradorM::join('hrm_dados','hrm_colaboradores.id_dado','hrm_dados.id_dado')
                               ->where('sts_colaborador','>',0)->get();
  }

  public function index()  {
    TI_sgs_log($this->rota['rota'],'index'); // REG_LOG
    $this->carrega();

    return view('MRP.'.$this->rota['rota'], ['rota'=>$this->rota]);
  }

  public function store(Request $request, MovimentoM $id)  {
    $data = $request->all();
    MRP_up_estoque($data);
    $log = $id->create($data);
    TI_sgs_log($this->rota['rota'],'store',$log['id_'.$this->rota['rota']]); // REG_LOG

    if(isset($data['mais'])){
      $this->carrega();
      $this->rota['insert'] = ['id_estoque'=>$data['id_estoque'],'id_mrp_tipo'=>$data['id_mrp_tipo']];
      return view('MRP.'.$data['mais'], ['rota'=>$this->rota]);
    }
    return redirect()->back()->with(['success' => 'Cadastrado com sucesso.']);
  }

  public function edit($id)  {
    $this->carrega();
    if($this->rota['acl']->u == 0) return redirect()->back()->with(['danger' => 'Sem acesso.']);
    $this->rota['edit'] = MovimentoM::findOrFail($id);

    return view('MRP.'.$this->rota['rota'], ['rota'=>$this->rota]);
  }

  public function update(Request $request, $id)  {
    $data = $request->all();

    $idUP = MovimentoM::findOrFail($id);
    TI_sgs_log($this->rota['rota'],'update',$id,$idUP); // REG_LOG
    $idUP->update($request->all());

    return redirect()->route($this->rota['rota'].'.index')->with(['success' => $this->rota['rota'].' alterado com sucesso.']);
  }

  public function destroy($id)  {
    TI_sgs_log($this->rota['rota'],'destroy',$id); // REG_LOG
    $id = MovimentoM::findOrFail($id);
    $id->update(['sts_'.$this->rota['rota'] => 0]);

    return redirect()->route($this->rota['rota'].'.index')->with(['success' => $this->rota['rota'].' excluído com sucesso.']);
  }
}

app/Http/Controllers/MRP/PedidoC.php
<?php namespace App\Http\Controllers\MRP;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\MRP\PedidoM;

class PedidoC extends Controller
{
  public $rota = ['rota' => 'pedido','pasta'=>'MRP/PED/'];

  public function carrega()  {
    $this->rota = TI_acl(H_colaboradorMRP(H_mrp_tipo($this->rota,32)));

    $this->rota[$this->rota['rota']] = PedidoM::where(function($query){
      $p = $this->rota['acl'];
      $query->where('sts_'.$this->rota['rota'],'>',0);

      if($p->a == 0 and $p->b == 0) $query->where('id_colaborador',\Auth::user()->id);
    })->get();

  }

  public function status($id)  {
    $ret = MRP_up_sts_pedido($id);
    TI_sgs_log($this->rota['rota'],'status',$id,$ret['OLD']); // REG_LOG {ROTA|METODO|ID|OLD}

    return redirect()->route($this->rota['rota'].'.index')->with($ret['with']);
  }

  public function index()  {
    TI_sgs_log($this->rota['rota'],'index'); // REG_LOG {ROTA|METODO|ID|OLD}
    $this->carrega();

    return view('MRP.'.$this->rota['rota'], ['rota'=>$this->rota]);
  }

  public function store(Request $request, PedidoM $id)  {
    $data = $request->all();
    $log = $id->create($data);
    TI_sgs_log($this->rota['rota'],'store',$log['id_'.$this->rota['rota']]); // REG_LOG {ROTA|METODO|ID|OLD}

    $show = ['id'=>$log['id_'.$this->rota['rota']],'rota'=>$this->rota['rota']];
    return redirect()->route('mrp_item.show',$show)->with(['success' => 'Cadastrado com sucesso.']);
  }

  public function edit($id)  {
    $this->carrega();
    if($this->rota['acl']->u == 0) return redirect()->back()->with(['danger' => 'Sem acesso.']);
    $this->rota['edit'] = PedidoM::findOrFail($id);

    return view('MRP.'.$this->rota['rota'], ['rota'=>$this->rota]);
  }

  public function update(Request $request, $id)  {
    $data = $request->all();

    $idUP = PedidoM::findOrFail($id);
    TI_sgs_log($this->rota['rota'],'update',$id,$idUP); // REG_LOG {ROTA|METODO|ID|OLD}
    $idUP->update($request->all());

    return redirect()->route($this->rota['rota'].'.index')->with(['success' => $this->rota['rota'].' alterado com sucesso.']);
  }

  public function destroy($id)  {
    TI_del_fluxo($this->rota['rota'],$id);
    TI_sgs_log($this->rota['rota'],'destroy',$id); // REG_LOG {ROTA|METODO|ID|OLD}
    $id = PedidoM::findOrFail($id);
    $id->update(['sts_'.$this->rota['rota'] => 0]);

    return redirect()->route($this->rota['rota'].'.index')->with(['success' => $this->rota['rota'].' excluído com sucesso.']);
  }
}

resources/views/MRP/kit.blade.php
@extends('layouts.sgs')

@section('content')
  @php
  $idP = 0;
  $acl = $rota['acl'];
  if(isset($rota['edit'])) {
    $idP = $rota['edit']->id_produto;
  }
  @endphp
  <main class="main">
    <br>
    <div class="container-fluid">
      <div class="row justify-content-center">
        <div class="col-md-12">

          @component('includes/alerts')
          @endcomponent

          <div class="card">
            {{-- FORM CADASTRO --}}
            <div class="card-header">
              @if (isset($rota['edit']))
                <form action="{{ route($rota['rota'].'.update',$rota['edit']['id_'.$rota['rota']]) }}" method="post" class="form">
                @method('PUT')
              @else
                <form action="{{ route($rota['rota'].'.store') }}" method="post" class="form">
                  <input type="hidden" name="id_colaborador" value="{{ Auth::user()->id }}">
                  <input type="hidden" name="rota" value="documento">
                @endif
                @csrf
                <div class="row justify-content-between">
                  <div class="col-8">
                    <div class="form-group">
                      <label for="exampleInputName2">KIT DE PRODUTOS </label>
                    </div>
                  </div>
                  {{-- ACL FORM CAD --}}
                  <div class="col-1">
                    @if ($acl->c == 1)
                        <button id="btn-plus" type="button" class="btn btn-pill btn-outline-success ml-3" onclick="Mostra_form_table('{{$rota['rota']}}')">
                          <i class='fa fa-plus'></i>
                        </button>
                      @endif
                  </div>
                  {{-- ACL FORM CAD --}}
                </div>

                  <div id="div-cad-{{$rota['rota']}}" class="{{isset($rota['edit'])?'divOpen':'divClose'}}" style="display: none">
                    <div class="row">

                      <div class="col-4">
                        <div class="input-group">
                          <div class="input-group-prepend">
                            <span class="input-group-text">Nome</span>
                          </div>
                          <input type="text" name="kit" class="form-control" value="{{ $rota['edit']->kit or old('kit') }}" oninput="this.value = this.value.toUpperCase()">
                        </div>
                      </div>

                      <button type="submit" class="btn btn-outline-success" id="submit">
                        {{ isset($rota['edit'])?"Salvar":"Cadastrar"}}
                      </button>
                    </div>

                  </div>
                </form>
              </div>
              {{-- END FORM --}}
              {{-- START LIST --}}
              <div class="car-body">
                {{-- DATATABLE --}}
                <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer mt-3">
                  <div id="div-list-{{$rota['rota']}}" class="{{isset($rota['edit'])?'divClose':'divOpen'}}">

                  <table class="table table-striped table-hover datatable dataTable no-footer table-sm" id="DataTables_Table_1" role="grid"
                  aria-describedby="DataTables_Table_0_info" style="border-collapse: collapse !important">
                  <thead>
                    <tr role="row">
                      <th class="sorting_asc" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Username: activate to sort column descending" style="width: 215px;">
                        Unidade
                      </th>
                      <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Date registered: activate to sort column ascending" style="width: 184px;">
                        COD
                      </th>
                      <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Role: activate to sort column ascending" style="width: 79px;">
                        Ação
                      </th>
                    </tr>
                  </thead>
                </div>
                  {{-- LIST --}}
                  <tbody>
                    @foreach ($rota[$rota['rota']] as $key)
                      <tr>
                        <td>{{ $key[$rota['rota']] }}</td>
                        <td>{{ $key->cod }}</td>
                        <td>
                          {{-- ACL ACOES TABLE --}}
                          <div class="row">
                              <div class="">
                                <a href="{{route('kit_item.show',$key['id_'.$rota['rota']]) }}" class="btn btn-block btn-ghost-success" title="Abrir kit">
                                  <i class="fas fa-toolbox"></i>
                                </a>
                              </div>

                            @if ($acl->u == 1)
                              <div class="">
                                <a href="{{route($rota['rota'].'.edit',$key['id_'.$rota['rota']]) }}" class="btn btn-block btn-ghost-warning" title="Editar">
                                  <i class="far fa-edit"></i>
                                </a>
                              </div>
                            @else
                              <div class="btn text-secondary"><i class="far fa-edit"></i></div>
                            @endif

                            @if ($acl->d == 1)
                              <div class="">
                                <form method="POST" action="{{route($rota['rota'].'.destroy',$key['id_'.$rota['rota']]) }}">
                                  @csrf
                                  @method('DELETE')
                                  <button type="submit" class="btn btn-block btn-ghost-danger" title="Excluir" onclick="return confirm('Confirma a exclusão?')">
                                    <i class="far fa-trash-alt"></i>
                                  </button>
                                </form>
                              </div>
                            @else
                              <div class="btn text-secondary"><i class="far fa-trash-alt"></i></div>
                            @endif
                          </div>
                          {{-- ACL ACOES TABLE --}}
                        </td>
                    </tr>
                  @endforeach
                </tbody>
              </table>

              <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="display: none;" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h4 class="modal-title">DOCUMENTO</h4>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      <p>One fine body…</p>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                    </div>
                  </div>

                </div>

              </div>
            </div>
            </div>

          </div>
        </div>

      </div>
    </div>
  </main>
@endsection