routes/web.php
<?php
Route::get('/', function () { return view('auth/entrar'); });
Route::get('/login', function () { return view('auth/entrar'); });
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
// EXCEL
Route::get('import-export-view', 'ExcelController@importExportView')->name('import.export.view');
Route::post('import-file', 'ExcelController@importFile')->name('import.file');
Route::get('export-file/{type}', 'ExcelController@exportFile')->name('export.file');
// ROUTE ADM
Route::prefix('ADM')->group(function () {
  Route::resource('/adm_tipo', 'ADM\TipoC');
  Route::resource('/adm_item', 'ADM_ItemC');
  Route::post('/aprovaOrc/{id}', 'ADM\OrcamentoC@aprovaOrc')->name('aprovaOrc');
  Route::resource('/compra', 'ADM\CompraC');
  Route::resource('/g_link', 'ADM\G_LinkC');
  Route::resource('/link', 'ADM\LinkC');
  Route::resource('/orcamento', 'ADM\OrcamentoC');
  Route::resource('/pessoa', 'ADM\PessoaC');
  Route::resource('/ramo', 'EMP\RamoC');
});
//  ROUTE EMP
Route::prefix('EMP')->group(function () {
  Route::resource('/empresa', 'EMP\EmpresaC');
  Route::resource('/emp_tipo', 'EMP\TipoC');
  Route::resource('/inventario', 'EMP_InventarioC');
  Route::resource('/setor', 'EMP\SetorC');
  Route::resource('/emp_item', 'EMP_ItemC');
  Route::resource('/emp_emprestimo', 'EMP\EmprestimoC');
  Route::resource('/documento', 'TI\DocumentoC');
});
// ROUTE HRM
Route::prefix('HRM')->group(function () {
  Route::resource('/hrm_arq', 'TI\ArquivoC');
  Route::resource('/cargo', 'HRM\CargoC');
  Route::resource('/certificado', 'HRM\CertificadoC');
  Route::resource('/colaborador', 'HRM\ContratoC');
  Route::resource('/contrato', 'HRM\ContratoC');
  Route::resource('/curriculo', 'HRM\CurriculoC');
  Route::resource('/curso', 'HRM\CursoC');
  Route::resource('/exame', 'HRM\ExameC');
  Route::resource('/ferias', 'HRM\FeriasC');
  Route::resource('/ferias_pagto', 'HRM\Ferias_PagtoC');
  Route::resource('/hrm_tipo', 'HRM\TipoC');
  Route::resource('/dependente', 'HRM\DependenteC');
});
// ROUTE LOG - FROTA
Route::prefix('LOG')->group(function () {
  Route::resource('/abastecimento', 'LOG\AbastecimentoC');
  Route::resource('/documento', 'LOG\DocumentoC');
  Route::resource('/log_tipo', 'LOG\TipoC');
  Route::resource('/manutencao', 'LOG\ManutencaoC');
  Route::resource('/multa', 'LOG\MultaC');
  Route::resource('/ocorrencia', 'LOG\OcorrenciaC');
  Route::resource('/vei_seg', 'LOG\Vei_SegC');
  Route::resource('/veiculo', 'LOG\VeiculoC');
  Route::resource('/vistoria', 'LOG\VistoriaC');
});
// ROUTE LOG - MRP
Route::prefix('MRP')->group(function () {
  Route::post('/baixa_item', 'MRP\ItemC@baixa')->name('baixa_item');
  Route::resource('/emprestimo', 'MRP_EmprestimoC');
  Route::resource('/estoque', 'MRP\EstoqueC');
  Route::resource('/kit', 'MRP\KitC');
  Route::resource('/kit_item', 'MRP\Kit_ItemC');
  Route::resource('/movimento', 'MRP\MovimentoC');
  Route::post('/mrp_filtro', 'MRP\EstoqueC@mrp_filtro')->name('mrp_filtro');
  Route::resource('/mrp_item', 'MRP\ItemC');
  Route::resource('/mrp_tipo', 'MRP\TipoC');
  Route::resource('/pedido', 'MRP\PedidoC');
  Route::resource('/produto', 'MRP\ProdutoC');
  Route::get('/sts_pedido/{id}', 'MRP\PedidoC@status')->name('sts_pedido');
  Route::resource('/und', 'MRP\UndC');
});
// ROUTE TI
Route::prefix('TI')->group(function () {
  Route::resource('/help', 'TI\HelpC');
  Route::resource('/modulo', 'TI\ModuloC');
  Route::resource('/permissao', 'TI\AclC');
  Route::resource('/produtoENT', 'MRP_ProdutoEntC');
  Route::resource('/ti_tipo', 'TI\TipoC');
  Route::resource('/update', 'TI\UpdateC');
  Route::resource('/usuario', 'TI\UsuarioC');
});

/*
GET       /photos	               index	   photos.index
GET	      /photos/create	       create	   photos.create
POST	    /photos	               store	   photos.store
GET	      /photos/{photo}	       show	     photos.show
GET	      /photos/{photo}/edit   edit	     photos.edit
PUT/PATCH	/photos/{photo}        update	   photos.update
DELETE	  /photos/{photo}	       destroy	 photos.destroy
*/

resources/views/includes/alerts.blade.php
<!-- MESSAGE ALERT -->
<div>
  <!-- MESSAGE ALERT SUCCESS -->
  @if (session('success'))
    {{ TI_alerta("success",session('success')) }}
  @endif
  <!-- MESSAGE ALERT SUCCESS -->
  <!-- MESSAGE ALERT DANGER -->
  @if (session('danger'))
    {{ TI_alerta("error",session('danger')) }}
  @endif
  <!-- MESSAGE ALERT DANGER -->
  <!-- MESSAGE ALERT INFO -->
  @if (session('info'))
    {{ TI_alerta("info",session('info')) }}
  @endif
  <!-- MESSAGE ALERT INFO -->
  <!-- MESSAGE ALERT ALERTA -->
  @if (session('warning'))
    {{ TI_alerta("warning",session('warning')) }}
  @endif
  <!-- MESSAGE ALERT ALERTA -->
</div>
<!-- MESSAGE ALERT   -->
<!-- MESSAGE ALERT -->
{{-- <div>
  <!-- MESSAGE ALERT SUCCESS -->
  @if (session('success'))
    <script>setTimeout("document.getElementById('alerta-1').style.display = 'none'", 5000););</script>
    <p id="alerta-1" class="alert alert-success">{{ session('success') }}</p>
    @php
      echo "<script>toastr.info('OK sucesso.');</script>";
    @endphp
    <a class="btn btn-info" onblur="toastr.info('OK sucesso.');">Info message</a>
  @endif
  <!-- MESSAGE ALERT SUCCESS -->
  <!-- MESSAGE ALERT DANGER -->
  @if (session('danger'))
    <script>setTimeout("document.getElementById('alerta-1').style.display = 'none'", 5000);</script>
    <p id="alerta-1" class="alert alert-danger">{{ session('danger') }}</p>
  @endif
  <!-- MESSAGE ALERT DANGER -->
</div> --}}
<!-- MESSAGE ALERT   -->

resources/views/includes/footer.blade.php
<footer class="app-footer">
  <div>
    <a href="#">SGS v{{ $_SESSION['versao']->versao }}</a>
    <span>© {{ date("Y")}} Sistema de Gestão Sinergia.</span>
  </div>
  <div class="ml-auto">
    <span>Desenvolvido por</span>
    <a href="#">Sinergia-TI</a>
  </div>
</footer>

<script src="{{ asset('js/jquery.min.js') }}"></script>
<script src="{{ asset('js/jquery.mask.min.js') }}"></script>
<script src="{{ asset('js/popper.min.js') }}"></script>
{{-- <script src="{{ asset('js/tooltip.js') }}"></script> --}}
<script src="{{ asset('js/bootstrap.min.js') }}"></script>
<script src="{{ asset('vendors/pace-progress/js/pace.min.js') }}"></script>
<script src="{{ asset('vendors/perfect-scrollbar/js/perfect-scrollbar.min.js') }}"></script>
<script src="{{ asset('vendors/coreui-pro/js/coreui.min.js') }}"></script>

<script type="text/javascript" src="{{ asset('js/jquery.dataTables.js') }}" class="view-script"></script>
<script type="text/javascript" src="{{ asset('js/dataTables.bootstrap4.js') }}" class="view-script"></script>
<script type="text/javascript" src="{{ asset('js/datatables.js') }}" class="view-script"></script>
{{-- <script type="text/javascript" src="{{ asset('js/bootstrap-select.min.js') }}" class="view-script"></script> --}}

<script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
<script type="text/javascript" src="https://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<script type="text/javascript" src="{{ asset('bootstrap-dynamic-tabs/bootstrap-dynamic-tabs.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/abas.js') }}"></script>
{{-- ALERT --}}
<script type="text/javascript" src="{{ asset('vendors/toastr.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/toastr.js') }}"></script>

<script src="{{ asset('vendors/daterangepicker.js') }}"></script>
<script src="{{ asset('vendors/select2.min.js') }}"></script>
<script src="{{ asset('js/advanced-forms.js') }}"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
<script type="text/javascript">
$(document).ready(function() {
    $('.js-example-basic-single').select2();
});

$('#ui-view').ajaxLoad();
$(document).ajaxComplete(function() {
  Pace.restart()
});

</script>

resources/views/includes/head.blade.php
@php
$sty = 'style-dark.css';
$name = Route::currentRouteName();
@endphp

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
  <meta name="description" content="SGS Sistema de Gestão Sinergia">
  <meta name="author" content="Ederson Carmo">
  <meta name="keyword" content="Bootstrap,Admin,Template,Open,Source,jQuery,CSS,HTML,RWD,Dashboard">
  <title>SGS  {{ Request::segment(1).'.'.ucfirst(Request::segment(2))}}</title>
  <link rel="shortcut icon" href="{{ asset('img/favicon.ico') }}" type="image/x-icon" />

  <link href="{{ asset('css/coreui-icons.min.css') }}" rel="stylesheet">
  <link href="{{ asset('css/flag-icon.min.css')    }}" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
  <link href="https://coreui.io/demo/dark/vendors/simple-line-icons/css/simple-line-icons.css" rel="stylesheet">

  <link href="{{ asset('css/'.$sty) }}" rel="stylesheet">

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="{{ asset('bootstrap-dynamic-tabs/bootstrap-dynamic-tabs.css') }}">
  {{-- ALERT --}}
  <link rel="stylesheet" href="{{ asset('css/toastr.min.css') }}"> 


  <link href="{{ asset('css/dataTables.bootstrap4.css') }}" rel="stylesheet">
  <link href="{{ asset('css/styleSGS.css') }}" rel="stylesheet">
  <link rel="stylesheet" href="{{ asset('css/daterangepicker.min.css') }}">
  <link href="{{ asset('css/select2.min.css') }}" rel="stylesheet">

                    {{-- <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" /> --}}
</head>

resources/views/includes/menu.blade.php
{{-- {{dd($_SESSION['teste'])}} --}}
<header class="app-header navbar" style="background-color:#02918D">
  <button class="navbar-toggler sidebar-toggler d-lg-none mr-auto" type="button" data-toggle="sidebar-show">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="{{ route('home') }}">
    <img class="navbar-brand-full" src="{{ asset('img/logo.png') }}" width="89" height="25" alt="Sinergia">
    <img class="navbar-brand-minimized" src="{{ asset('img/favicon.png') }}" width="30" height="30" alt="Sinergia Logo">
  </a>

  <button class="navbar-toggler sidebar-toggler d-md-down-none" type="button" data-toggle="sidebar-lg-show">
    <span class="navbar-toggler-icon"></span>
  </button>

  <ul class="nav navbar-nav d-md-down-none">

    @foreach ($_SESSION['menu'] as $key)
      @if ($key->permissoes->r == 1 AND $key->sts_modulo == 1)
        <div class="dropdown show">
          <li class="nav-item px-2">
            <button class="btn btn-link dropdown-toggle text-white" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" title="{{ $key->modulo }}">
              {{ strlen($key->modulo) > 12 ? $key->cod:$key->modulo }}
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, 35px, 0px);">
              @foreach ($_SESSION['menu'] as $key1)
                @if ($key1->modulo_id == $key->id_modulo && $key1->permissoes['r'] == 1 && $key1->sts_modulo < 4)
                  <a class="dropdown-item" href="{{ $key1->rota == 'null'? '#': route($key1->rota.'.index') }}" onmouseover="MudaEstadoMenu('div-menu-{{$key1->id_modulo}}')">{{ $key1->modulo }}</a>

                  @foreach ($_SESSION['menu'] as $key2)
                    @if ($key2->modulo_id == $key1->id_modulo && $key2->permissoes['r'] == 1)

                      <div id="div-menu-{{$key1->id_modulo}}" class="divClose">
                        @foreach ($_SESSION['menu'] as $key3)
                          @if ($key3->modulo_id == $key1->id_modulo && $key3->permissoes['r'] == 1)
                            <div class="row">
                              <div class="col-9">
                                <a class="dropdown-item bg-secondary" href="{{ route($key3->rota.'.index') }}">{{ $key3->modulo }}</a>
                              </div>
                              <div class="col-3">
                                <a class="text-dark" target="new" href="{{ route($key3->rota.'.index') }}"><i class="fas fa-angle-double-right"></i></a>
                              </div>
                            </div>
                          @endif
                        @endforeach
                      </div>

                    @endif
                  @endforeach

                @endif
              @endforeach
            </div>
          </li>
        </div>
      @endif
    @endforeach

  </ul>
{{-- ALERT BARRA MENU --}}
  <ul class="nav navbar-nav ml-auto">
    <li class="nav-item dropdown d-md-down-none">
      <a class="nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        <i class="icon-bell"></i>
        <span class="badge badge-pill badge-danger">5</span>
      </a>
      <div class="dropdown-menu dropdown-menu-right dropdown-menu-lg">
        <div class="dropdown-header text-center">
          <strong>You have 5 notifications</strong>
        </div>
        <a class="dropdown-item" href="#">
          <i class="icon-user-follow text-success"></i> New user registered
        </a>
        <a class="dropdown-item" href="#">
          <i class="icon-user-unfollow text-danger"></i> User deleted
        </a>
        <a class="dropdown-item" href="#">
          <i class="icon-chart text-info"></i> Sales report is ready
        </a>
        <a class="dropdown-item" href="#">
          <i class="icon-basket-loaded text-primary"></i> New client
        </a>
        <a class="dropdown-item" href="#">
          <i class="icon-speedometer text-warning"></i> Server overloaded
        </a>
      </div>
    </li>
    {{-- ALERT BARRA MENU --}}
    </ul>
    <button class="navbar-toggler aside-menu-toggler d-md-down-none" type="button" data-toggle="aside-menu-lg-show">
      <img class="img-avatar" width="50" height="50" src="{{ asset('storage/TI/USER/'.Auth::user()->arquivo) }}" alt="{{ Auth::user()->email }}" title="{{ Auth::user()->name }}">
    </button>
    <button class="navbar-toggler aside-menu-toggler d-lg-none" type="button" data-toggle="aside-menu-show">
      <img class="img-avatar" width="50" height="50" src="{{ asset('storage/TI/USER/'.Auth::user()->arquivo) }}" alt="{{ Auth::user()->email }}" title="{{ Auth::user()->name }}">
    </button>


  </header>

resources/views/includes/menu_dir.blade.php
@php
$idT = 0;
if(isset($rota['edit'])){
  $idT = $rota['edit']->id_ti_tipo;
}
@endphp
<!-- MENU MENU MENU  -->
<aside class="aside-menu">
  <ul class="nav nav-tabs" role="tablist">
    {{-- <li class="nav-item">
    <a class="nav-link active" data-toggle="tab" href="#timeline" role="tab">
    <i class="icon-speech"></i>
  </a>
</li> --}}
<li class="nav-item">
  <a class="nav-link" data-toggle="tab" href="#links" role="tab" title="Links">
    <i class="fas fa-list"></i>
  </a>
</li>
<li class="nav-item">
  <a class="nav-link" data-toggle="tab" href="#settings" role="tab" title="Configurações">
    <i class="fas fa-cogs"></i>
  </a>
</li>
<li class="nav-item">
  <a class="nav-link" data-toggle="tab" href="#perfil" role="tab" title="Perfil">
    <i class="fas fa-user-cog"></i>
  </a>
</li>
<li class="nav-item">
  <a class="nav-link" data-toggle="tab" href="{{ route('logout') }}" role="tab" title="Sair do SGS"
  onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
  <i class="fas fa-sign-out-alt"></i>
</a>

<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
  @csrf
</form>
</li>
</ul>

<div class="tab-content">

{{-- MENU LINKS --}}
    <div class="tab-pane active p-3" id="links" role="tabpanel">
      <h6>Links</h6>
      {{-- LINKS LIVRES --}}
      @foreach ($_SESSION['links'] as $key)
          @if ($key->id_modulo == null)
            <div class="message">
              <div class="row">
                <div class="col-5">
                  <a class="nav-link" data-toggle="tab" href="#links" role="tab" title="Editar">
                    <div class="text-truncate font-weight-bold">{{ $key->g_link }}</div>
                  </a>
                </div>
                <div class="col-7">
                  @foreach ($key->links as $key1)
                    <a href="{{ $key1->url }}"><small class="text-white">{{ $key1->link }}</small></a>
                  @endforeach
                </div>
              </div>
            </div>
            <hr>
          @endif
      {{-- LINKS PARA MODULOS --}}
        @foreach ($_SESSION['menu'] as $keyM)
          @if ($key->id_modulo == $keyM->id_modulo)
            <div class="message">
              <div class="row">
                <div class="col-5">
                  <a class="nav-link" data-toggle="tab" href="#links" role="tab" title="Editar">
                    <div class="text-truncate font-weight-bold">{{ $key->g_link }}</div>
                  </a>
                </div>
                <div class="col-7">
                  @foreach ($key->links as $key1)
                    <a href="{{ $key1->url }}"><small class="text-white">{{ $key1->link }}</small></a>
                  @endforeach
                </div>
              </div>
            </div>
            <hr>
          @endif
        @endforeach
      @endforeach
      {{-- <a class="nav-link" data-toggle="tab" href="#links" role="tab" title="Cadastrar links">
        <i class="icon-plus"></i>
      </a> --}}

    </div>
    {{-- MENU CONFIGURAÇÕES --}}
    <div class="tab-pane p-3" id="settings" role="tabpanel">
      {{-- <h6>Configurações</h6>
      <div class="aside-options">
        <div class="clearfix mt-4">
          <small>
            <b>Cor de fundo</b>
          </small>
          <label class="switch switch-label switch-pill switch-success switch-sm float-right">
            <input class="switch-input" type="checkbox" >
            <span class="switch-slider" data-checked="BR" data-unchecked="PT"></span>
          </label>
        </div>
        <div>
          <small class="text-muted">'BR' ativa o fundo banco.<br> 'PT' ativa o fundo preto.</small>
        </div>
      </div>
      <div class="aside-options">
        <div class="clearfix mt-3">
          <small>
            <b>Mostra menu lateral</b>
          </small>
          <label class="switch switch-label switch-pill switch-success switch-sm float-right">
            <input class="switch-input" type="checkbox" checked>
            <span class="switch-slider" data-checked="Sim" data-unchecked="Não"></span>
          </label>
        </div>
        <div>
          <small class="text-muted">Lorem ipsum dolor sit amet.</small>
        </div>
      </div>
      <div class="aside-options">
        <div class="clearfix mt-3">
          <small>
            <b>Option 3</b>
          </small>
          <label class="switch switch-label switch-pill switch-success switch-sm float-right">
            <input class="switch-input" type="checkbox">
            <span class="switch-slider" data-checked="On" data-unchecked="Off"></span>
          </label>
        </div>
      </div>
      <div class="aside-options">
        <div class="clearfix mt-3">
          <small>
            <b>Option 4</b>
          </small>
          <label class="switch switch-label switch-pill switch-success switch-sm float-right">
            <input class="switch-input" type="checkbox" checked="">
            <span class="switch-slider" data-checked="On" data-unchecked="Off"></span>
          </label>
        </div>
      </div>
      <hr> --}}
      <h6>HelpDesk</h6>
      <form action="{{ route('help.store') }}" method="post" class="form" enctype="multipart/form-data">
        <input type="hidden" name="id_solicitante" value="{{ Auth::user()->id }}">
        @csrf

        <div class="mt-3">
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text"><i class="fa fa-commenting-o"></i></span>
            </div>
            <textarea id="textarea-input" name="help" rows="3" class="form-control">{{ $rota['edit']->help or '' }}</textarea>
          </div>
        </div>

        <div class="mt-3">
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text">Tipo</span>
            </div>
            <select id="select1" name="id_ti_tipo" class="form-control">
              @foreach ($_SESSION['tipos'] as $key)
                <option value="{{ $key->id_ti_tipo }}" {{ $key->id_ti_tipo==$idT?"selected":"" }}>
                  {{ $key->ti_tipo }}
                </option>
              @endforeach
            </select>
          </div>
        </div>

        <div class="mt-3">
          <div class="input-group">
            <input id="arquivo" type="file" name="arquivo" class="form-control" value="{{ $rota['edit']->arquivo or old('arquivo') }}">
          </div>
        </div>

        <button type="submit" class="btn btn-outline-success btn-block mt-3" id="submit">
          Abrir Chamado
        </button>

      </form>
      <hr>
      @foreach ($_SESSION['help'] as $key)
        @php
        switch ($key->sts_help) {
          case '0': $cor = 'dark';      $tx = 'Cancelado';  break;
          case '1': $cor = 'warning';   $tx = 'Pendente';   break;
          case '2': $cor = 'secondary'; $tx = 'Na fina';    break;
          case '3': $cor = 'info';      $tx = 'Em analise'; break;
          case '4': $cor = 'light';     $tx = 'Retronado';  break;
          case '5': $cor = 'success';   $tx = 'Finalizado'; break;
          default:  $cor = 'dark';      $tx = 'Erro';       break;
        }
        @endphp
        @if ($key->id_solicitante == Auth::user()->id)
          <div class="row">
            @if ($key->sts_help > 3)
              <a href="#" class="card-header-action btn-maximize text-success" data-toggle="collapse" data-target="#help-{{$key->id_help}}" aria-expanded="true">
                <i class="fas fa-search-plus ml-1"></i>
              </a>
            @else
              <i class="fas fa-search ml-2 mr-1"></i>
            @endif
              {{ $key->id_help }}_{{ substr($key->help, 0, 25) }}
              <i class="fas fa-tag text-{{$cor}}" title="{{$tx}}"></i><br>
          </div>
          @if ($key->sts_help > 3)
          <div class="card">
            <div class="card-body collapse" id="help-{{$key->id_help}}">
              {{$key->solucao}}
            </div>
          </div>
          @endif

        @endif
      @endforeach
    </div>
    {{-- MENU CONFIGURAÇÕES --}}
    {{-- MENU PERFIL --}}
    <div class="tab-pane p-3" id="perfil" role="tabpanel">
      <h6>Perfil: {{ Auth::user()->name }}</h6>

      <form action="{{ route('usuario.update', Auth::user()->id) }}" method="post" enctype="multipart/form-data">
        @method('PUT')
        @csrf
        <div class="mt-3">
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text">Nome</span>
            </div>
            <input type="text" name="name" class="form-control" value="{{ Auth::user()->name }}">
          </div>
        </div>

        <div class="mt-3">
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text">Cel</span>
            </div>
            <input type="text" name="cel" class="form-control">
          </div>
        </div>

        <div class="mt-3">
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text">Email</span>
            </div>
            <input type="email" name="email" class="form-control" value="{{ Auth::user()->email }}" disabled>
            <input type="hidden" name="email" class="form-control" value="{{ Auth::user()->email }}">
          </div>
        </div>

        <div class="mt-3">
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text">Senha</span>
            </div>
            <input type="password" name="passwordOld" class="form-control" value="">
          </div>
        </div>

        <div class="mt-3">
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text">Nova</span>
            </div>
            <input type="password" name="password" class="form-control" value="123456">
          </div>
        </div>

        <div class="mt-3">
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text">Repete</span>
            </div>
            <input type="password" name="password2" class="form-control" value="123456">
          </div>
        </div>

        <div class="mt-3">
          <div class="input-group">
            <input id="arquivo" type="file" name="arquivo" class="form-control" value="{{ $rota['edit']->arquivo or old('arquivo') }}">
          </div>
        </div>


        <button type="submit" class="btn btn-outline-success btn-block col-8 mt-3" id="submit">
          Salvar alterações
        </button>

      </form>

    </div>
    {{-- MENU PERFIL --}}
  </div>
</aside>
</div>